define GrumblingArray = [] 
label generate_GrumblingArray:
    $GrumblingArray.append('Мхм...')
    $GrumblingArray.append('Ммм...')
    $GrumblingArray.append('Ага.')
    $GrumblingArray.append('Таак.')
    $GrumblingArray.append('Угу..')
    $GrumblingArray.append('Мм.....')
    $GrumblingArray.append('Хммм.')
    $GrumblingArray.append('Хмм..')
    $GrumblingArray.append('Посмотрим...')
    $GrumblingArray.append('Секунду...')
    $GrumblingArray.append('Подожди...')
    $GrumblingArray.append('Угу..')
    $GrumblingArray.append('Ох..')
    $GrumblingArray.append('Оу!')
    $GrumblingArray.append('Уххх...')
    $GrumblingArray.append('Эхх..')
    $GrumblingArray.append('Уффф...')
    $GrumblingArray.append('Уф!')
    $GrumblingArray.append('Эх..')
    $GrumblingArray.append('Ээээ..')
    $GrumblingArray.append('Пфффф...')
    $GrumblingArray.append('*Вздыхает*')
    $GrumblingArray.append('Ох-хох...')
    $GrumblingArray.append('Хух...')
    $GrumblingArray.append('Фух...')
    #   return
