init python:
    import json
    import os



    store.database_items = [
    {
        "id": -1
    },
    {
        "id": 1,
        "name": "Стельки для бега",
        "description": "Заставляет вас бегать быстрее в гоночной мини-игре.",
        "price": 5,
        "disable_after_first_buy": "True",
        "disappear_after_first_buy": "False",
        "condition_visible": "True",
        "condition_enabled": "True",
        "limit": 1,
        "label_on_buy": "",
        "action_on_buy": "",
        "tags": "[\"general\"]",
        "null": ""
    },
    {
        "id": 2,
        "name": "Справка по набору текста",
        "description": "Добавляет 5 секунд к обратному отсчету для мини-игры обзора игр.",
        "price": 5,
        "disable_after_first_buy": "True",
        "disappear_after_first_buy": "False",
        "condition_visible": "True",
        "condition_enabled": "True",
        "limit": 1,
        "label_on_buy": "",
        "action_on_buy": "",
        "tags": "[\"general\"]",
        "null": ""
    },
    {
        "id": 12,
        "name": "Справка по обзору",
        "description": "Считается за завершение мини-игры обзора игр. Добавляет 2 [sa.say_name] очка.",
        "price": 5,
        "disable_after_first_buy": "False",
        "disappear_after_first_buy": "False",
        "condition_visible": "True",
        "condition_enabled": "True",
        "limit": 0,
        "label_on_buy": "",
        "action_on_buy": "review_help_item_action()",
        "tags": "[\"general\"]",
        "null": ""
    },
    {
        "id": 3,
        "name": "Мастер Математики",
        "description": "Устраняет один неправильный ответ из математической мини-игры.",
        "price": 5,
        "disable_after_first_buy": "True",
        "disappear_after_first_buy": "False",
        "condition_visible": "True",
        "condition_enabled": "True",
        "limit": 1,
        "label_on_buy": "",
        "action_on_buy": "",
        "tags": "[\"general\"]",
        "null": ""
    },
    {
        "id": 11,
        "name": "Словарь",
        "description": "Делает мини-игру чтение проще.",
        "price": 5,
        "disable_after_first_buy": "True",
        "disappear_after_first_buy": "False",
        "condition_visible": "True",
        "condition_enabled": "True",
        "limit": 1,
        "label_on_buy": "",
        "action_on_buy": "",
        "tags": "[\"general\"]",
        "null": ""
    },
    {
        "id": 4,
        "name": "Мотивационная Аудиокнига",
        "description": "Добавляет 1 XP Смелости.",
        "price": 5,
        "disable_after_first_buy": "False",
        "disappear_after_first_buy": "False",
        "condition_visible": "True",
        "condition_enabled": "True",
        "limit": 0,
        "label_on_buy": "",
        "action_on_buy": "stats.add_boldness_xp(1, yalign = 0.025)",
        "tags": "[\"general\"]",
        "null": ""
    },
    {
        "id": 5,
        "name": "Подарок для [sa.say_name]",
        "description": "Добавляет 4 [sa.say_name] очка.",
        "price": 4,
        "disable_after_first_buy": "False",
        "disappear_after_first_buy": "False",
        "condition_visible": "True",
        "condition_enabled": "True",
        "limit": 0,
        "label_on_buy": "",
        "action_on_buy": "sa.add_points(4, yalign = 0.025)",
        "tags": "[\"general\"]",
        "null": ""
    },
    {
        "id": 6,
        "name": "Подарок для [k.say_name]",
        "description": "Добавляет 4 [k.say_name] очка.",
        "price": 4,
        "disable_after_first_buy": "False",
        "disappear_after_first_buy": "False",
        "condition_visible": "True",
        "condition_enabled": "True",
        "limit": 0,
        "label_on_buy": "",
        "action_on_buy": "k.add_points(4, yalign = 0.025)",
        "tags": "[\"general\"]",
        "null": ""
    },
    {
        "id": 7,
        "name": "Подарок для [si.say_name]",
        "description": "Добавляет 4 [si.say_name] очка.",
        "price": 4,
        "disable_after_first_buy": "False",
        "disappear_after_first_buy": "False",
        "condition_visible": "True",
        "condition_enabled": "True",
        "limit": 0,
        "label_on_buy": "",
        "action_on_buy": "si.add_points(4, yalign = 0.025)",
        "tags": "[\"general\"]",
        "null": ""
    },
    {
        "id": 10,
        "name": "Подарок для [julia.say_name]",
        "description": "Добавляет 4 [julia.say_name] очка.",
        "price": 4,
        "disable_after_first_buy": "False",
        "disappear_after_first_buy": "False",
        "condition_visible": "store.had_julia_arrived_scene",
        "condition_enabled": "True",
        "limit": 0,
        "label_on_buy": "",
        "action_on_buy": "julia.add_points(4, yalign = 0.025)",
        "tags": "[\"general\"]",
        "null": ""
    },
    {
        "id": 13,
        "name": "Подарок для [janet.say_name]",
        "description": "Добавляет 4 [janet.say_name] очка.",
        "price": 4,
        "disable_after_first_buy": "False",
        "disappear_after_first_buy": "False",
        "condition_visible": "store.had_janet_intro_scene",
        "condition_enabled": "True",
        "limit": 0,
        "label_on_buy": "",
        "action_on_buy": "janet.add_points(4, yalign = 0.025)",
        "tags": "[\"general\"]",
        "null": ""
    },
    {
        "id": 14,
        "name": "Подарок для [edna.say_name]",
        "description": "Добавляет 4 [edna.say_name] очка.",
        "price": 4,
        "disable_after_first_buy": "False",
        "disappear_after_first_buy": "False",
        "condition_visible": "store.had_edna_intro_scene",
        "condition_enabled": "True",
        "limit": 0,
        "label_on_buy": "",
        "action_on_buy": "edna.add_points(4, yalign = 0.025)",
        "tags": "[\"general\"]",
        "null": ""
    },
    {
        "id": 8,
        "name": "Купальник для [sa.say_name]",
        "description": "Открывает небольшую сцену и наряд для [sa.say_name]. Покупка только в дневное время.",
        "price": 12,
        "disable_after_first_buy": "True",
        "disappear_after_first_buy": "False",
        "condition_visible": "True",
        "condition_enabled": "store.week.time == \"day\"",
        "limit": 1,
        "label_on_buy": "sam_scene_swimsuit",
        "action_on_buy": "",
        "tags": "[\"general\"]",
        "null": ""
    },
    {
        "id": 9,
        "name": "Купальник для [si.say_name]",
        "description": "Открывает небольшую сцену и наряд для [si.say_name]. Покупка только в дневное время.",
        "price": 12,
        "disable_after_first_buy": "True",
        "disappear_after_first_buy": "False",
        "condition_visible": "True",
        "condition_enabled": "store.week.time == \"day\"",
        "limit": 1,
        "label_on_buy": "simone_scene_swimsuit",
        "action_on_buy": "",
        "tags": "[\"general\"]",
        "null": ""
    },
    {
        "id": -1,
        "name": "End of list",
        "null": 0
    }
    ]