label simone_convo_default:
    call process_conversation_beginning ([ (n, ""), (si, "") ])

    call debug_message ("Default conversation when none others are available.")
    $ si.c("Привет " + n.say_name + ".")

    call process_end_of_conversation ("simone_convo_default", si, default=True, priority=False)

    return

label simone_convo_1:
    call process_conversation_beginning ([ (n, ""), (si, "pose handsfront face neutral") ])
    call process_character (si, appearance="pose handsfront face neutral", text="Мне нравится этот прекрасный район.")
    call process_character (si, appearance="pose handsfront face neutral", text="Здесь спокойно и дома выглядят чистыми.")
    call process_character (n, appearance="pose handpocket face neutral", text="Да, здесь очень тихо.")
    call process_character (si, appearance="pose handsfront face neutral", text="Но всё находится довольно далеко.")
    call process_character (si, appearance="pose handsfront face neutral", text="До продуктовых магазинов надо ехать 25 минут.")
    call process_character (si, appearance="pose armunder face neutral", text="Я совсем не подумала об этом, когда покупала дом!")
    call process_character (n, appearance="pose handpocket face neutral", text="А где [k.say_name] работает, там нет продуктовых магазинов?")
    call process_character (si, appearance="pose handsfront face neutral", text="Есть,{p=1.0}Но они не по пути.")
    call process_character (si, appearance="pose handsup face neutral", text="Мы просто должны тщательно планировать список покупок.")
    call process_character (n, appearance="pose twohandfist face neutral", text="Холодильник у нас огромный!{p=1.0}Так что мы всегда можем купить больше еды и заморозить.")
    call process_character (si, appearance="pose handsup face happy", text="Ха, думаю да.")
    call process_character (si, appearance="pose handsfront face neutral", text="Но когда мой сад начнёт давать плоды, нам не придется ходить по магазинам!")

    call process_end_of_conversation ("simone_convo_1", si, default=False, priority=False)

    return

label simone_convo_2:
    call process_conversation_beginning ([ (n, ""), (si, "pose armunder face neutral") ])
    call process_character (si, appearance="pose armunder face neutral", text="Как тебе новая комната, [n.say_name]?")
    call process_character (n, appearance="pose handpocket face neutral", text="Мне нравится.")
    call process_character (si, appearance="pose armunder face neutral", text="Она удобна?")
    call process_character (n, appearance="pose handpocket face neutral", text="Да.")
    call process_character (si, appearance="pose handsfront face neutral")
    $ si.c("Я не была уверена, как ты и " + sa.say_name + " отнесетесь к разделению.")
    call process_character (n, appearance="pose handpocket face neutral", text="Думаю, все в порядке.")
    call process_character (n, appearance="pose behindhead face neutral", text="Я почти часто захожу в комнату [sa.say_name].")
    call process_character (n, appearance="pose behindhead face neutral", text="Мы не видим друг друга только, когда спим.")
    call process_character (si, appearance="pose handsup face neutral", text="Похоже, вы двое составляете друг другу компанию.")
    call process_character (n, appearance="pose handpocket face neutral")
    $ n.c(sa.say_name + " держит в комнате всё для стриминга.")
    call process_character (si, appearance="pose armunder face neutral", text="Ах да, точно!{p=1.0}Вы ведь вдвоём стримите, а где?")
    $ renpy.pause(2)
    call process_character (si, appearance="pose armunder face embarrassed", text="\"[video_sharing_site_simone_wrong]?\"")
    call process_character (n, appearance="pose handpocket face neutral", text="[video_sharing_site] Мам.")
    call process_character (si, appearance="pose handsfront face happy", text="[video_sharing_site] ах да, точно!")
    call process_character (si, appearance="pose handsfront face happy", text="Я совсем ламер в компьютерах, как вы говорите.")
    call process_character (n, appearance="pose handpocket face neutral", text="Всё хорошо, мама..")
    call process_character (n, appearance="pose handfist face neutral")
    $ n.c(sa.say_name + " хочет, чтобы как можно больше людей смотрели наши видео.")
    call process_character (si, appearance="pose handsup face neutral", text="Это здорово, что вы оба упорно работаете вместе, чтобы добиться успеха!")
    call process_character (si, appearance="pose handsup face neutral", text="Нет ничего лучше, чем работа в команде!")

    call process_end_of_conversation ("simone_convo_2", si, default=False, priority=False)

    return

label simone_convo_3:
    call process_conversation_beginning ([ (n, ""), (si, "pose handsfront face neutral") ])
    call process_character (si, appearance="pose handsfront face neutral", text="Мама только что звонила.")
    call process_character (n, appearance="pose handpocket face curious", text="Мама?")
    call process_character (si, appearance="pose handsfront face neutral", text="Твоя бабушка.")
    call process_character (n, appearance="pose handpocket face happy", text="Ооо.")
    call process_character (n, appearance="pose handpocket face neutral", text="Да?{p=1.0}По какому поводу она звонила?")
    call process_character (si, appearance="pose handsup face neutral", text="Она сказала, что хотела бы нас навестить в ближайшее время.")
    call process_character (si, appearance="pose handsup face neutral", text="Я думаю, её дом всё ещё на ремонте.")
    call process_character (si, appearance="pose handsup face neutral", text="Так что трудно разместить ещё кого-нибудь там сейчас.")
    call process_character (n, appearance="pose twohandfist face neutral", text="Было бы весело вернуться на пляж!")
    call process_character (si, appearance="pose armunder face neutral", text="Прошло много времени с тех пор, как мы ходили.")
    call process_character (n, appearance="pose behindhead face neutral", text="Это был не тот ли раз, когда [k.say_name] играла в волейбол?")
    call process_character (si, appearance="pose handsup face neutral", text="О, да! Тот.")
    call process_character (si, appearance="pose handsup face neutral", text="Она втоптала в грязь всех, кто бросал ей вызов.")
    call process_character (n, appearance="pose behindhead face curious")
    $ n.c("" + k.say_name + " ударила мяч настолько сильно, что он отскочил от лица парня?")
    call process_character (si, appearance="pose handsup face happy", text="Было так неловко!")
    call process_character (si, appearance="pose handsup face happy", text="На лице бедняги была одна большая красная отметина.")
    call process_character (si, appearance="pose handsfront face neutral", text="Хотя это твоя сестра.")
    call process_character (si, appearance="pose handsfront face neutral", text="Она не берет пленных на соревнованиях.")

    call process_end_of_conversation ("simone_convo_3", si, default=False, priority=False)

    return

label simone_convo_4:
    call process_conversation_beginning ([ (n, ""), (si, "pose handsfront face neutral") ])
    call process_character (si, appearance="pose handsfront face neutral", text="Я очень впечатлена новой школой.")
    call process_character (n, appearance="pose handpocket face neutral", text="В смысле?")
    call process_character (si, appearance="pose handsfront face neutral", text="Ваш новый учитель звонил мне.")
    call process_character (si, appearance="pose handsfront face neutral", text="Мы очень мило поговорили")
    call process_character (n, appearance="pose handpocket face curious")
    $ renpy.pause(1)
    call process_character (n, appearance="pose handpocket face curious", text="Учитель звонил нам домой?")
    call process_character (si, appearance="pose handsup face neutral", text="Я была так же удивлена, как и ты.")
    call process_character (si, appearance="pose handsup face neutral", text="Но я считаю, что это хороший показатель.")
    call process_character (si, appearance="pose handsup face neutral", text="Это показывает, что они хотят поддерживать связь с родителями учащихся.")
    call process_character (n, appearance="pose behindhead face neutral", text="У нас только один учитель?")
    call process_character (si, appearance="pose handsfront face neutral", text="Это очень уникальная школа.")
    call process_character (si, appearance="pose handsfront face neutral", text="Им нравится, когда один учитель ведёт уроки для небольшой группы учеников.")
    call process_character (si, appearance="pose handsfront face neutral", text="Так вам комфортней учиться.")
    call process_character (n, appearance="pose handpocket face neutral", text="Интересно.")
    call process_character (si, appearance="pose armunder face neutral", text="Я думаю это замечательно.")
    call process_character (si, appearance="pose armunder face neutral", text="Это позволяет учителю уделять больше внимания каждому ученику.")
    call process_character (n, appearance="pose handpocket face concerned")
    $ n.c("" + sa.say_name + " будет в том же классе?")
    call process_character (si, appearance="pose handsup face neutral", text="Не волнуйся.{p=1.0}Я позаботилась о том, чтобы вы с сестрой были вместе.")
    call process_character (n, appearance="pose handpocket face neutral")
    call process_character (si, appearance="pose handsup face neutral", text="Обычно они держат братьев и сестер в разных классах, потому что они часто конфликтуют.")
    call process_character (si, appearance="pose handsup face neutral")
    $ si.c("Но я сказала ему, что ты и " + sa.say_name + " отлично ладите.")
    call process_character (n, appearance="pose handpocket face neutral", text="Учитель показался тебе милым?")
    call process_character (si, appearance="pose handsfront face neutral", text="По телефону она казалась очень вежливой.")
    call process_character (si, appearance="pose handsfront face neutral", text="Голос звучал, как у молоденькой учительницы.")
    call process_character (si, appearance="pose armunder face neutral")
    $ si.c("Возможно, она на несколько лет старше, чем " + k.say_name + ".")
    call process_character (n, appearance="pose handfist face neutral", text="Я рад, что у неё хороший голос.")
    call process_character (si, appearance="pose handsfront face neutral")
    $ si.c("Я думаю ты и " + sa.say_name + " понравится у неё учиться!")

    call process_end_of_conversation ("simone_convo_4", si, default=False, priority=False)

    return

label simone_convo_5:
    call process_conversation_beginning ([ (n, ""), (si, "pose handsup face neutral") ])
    call process_character (si, appearance="pose handsup face neutral", text="Я думаю, как здорово ты ладишь со своими сестрами! ")
    call process_character (n, appearance="pose behindhead face embarrassed", text="Ты столько раз мне это говорила, мама...")
    call process_character (si, appearance="pose handsfront face neutral", text="Ну, хорошие отношения с братьями и сестрами очень важны.")
    call process_character (n, appearance="pose handpocket face neutral")
    call process_character (si, appearance="pose handsfront face neutral", text="В наши дни это сложно.{p=1.0} По крайней мере я так думаю...")
    call process_character (n, appearance="pose handpocket face concerned", text="Разве ты не ладишь с тетушкой?")
    call process_character (si, appearance="pose handsup face neutral", text="Нуу...{p=1.0}Мы даем друг другу пространство.")
    call process_character (si, appearance="pose handsup face neutral", text="Я забочусь о своей сестре.")
    call process_character (si, appearance="pose armunder face neutral", text="Но она...")
    $ renpy.pause(2)
    call process_character (si, appearance="pose armunder face concerned", text="Говорит всё в лоб.")
    call process_character (n, appearance="pose behindhead face curious", text="В лоб?")
    call process_character (si, appearance="pose handsfront face neutral", text="Она всегда говорит, что думает.")
    call process_character (si, appearance="pose handsfront face concerned", text="Хорошо это или плохо.")
    call process_character (n, appearance="pose behindhead face concerned", text="О.")
    call process_character (si, appearance="pose handsup face neutral", text="Честность - это хорошее качество.")
    call process_character (n, appearance="pose handpocket face neutral")
    call process_character (si, appearance="pose handsup face neutral", text="Но так же важно быть вежливым и уважительным по отношению к другим.")
    call process_character (si, appearance="pose handsup face neutral", text="И я думаю, что твоей тёте выходит это боком.")
    call process_character (n, appearance="pose handpocket face curious", text="Интересно, поэтому она зовет меня \"коротышка\"?")
    call process_character (si, appearance="pose armunder face angry")
    $ si.c("Она также сказала мне, что я \"много ем\" и из-за этого ты и " + sa.say_name + ", не доедаете...")
    call process_character (n, appearance="pose handpocket face concerned", text="Я думаю, ты хорошо нас всех кормишь, мама.")
    call process_character (si, appearance="pose handsfront face concerned", text="Не верь всему, что твоя тетя говорит о людях, вот и всё..")

    call process_end_of_conversation ("simone_convo_5", si, default=False, priority=False)

    return


label simone_convo_6:
    call process_conversation_beginning ([ (n, "pose handpocket face concerned"), (si, "pose handsfront face neutral") ])
    $ renpy.pause(1)
    call process_character (si, appearance="pose handsfront face neutral", text="Как прошел твой день?")
    call process_character (n, appearance="pose behindhead face concerned")
    $ renpy.pause(1)
    call process_character (n, appearance="pose behindhead face concerned", text="Хорошо.")
    call process_character (si, appearance="pose handsup face curious")
    $ si.c("Я хотела узнать у тебя, " + n.say_name + "...")
    call process_character (n, appearance="pose handpocket face curious", text="Хм?")
    call process_character (si, appearance="pose armunder face neutral", text="Когда ты был в ванной, и я увидела тебя.")
    call process_character (n, appearance="pose behindhead face curious blush true")
    $ renpy.pause(1)
    call process_character (n, appearance="pose behindhead face curious blush true", text="Д-да?")
    call process_character (si, appearance="pose handsfront face neutral", text="Я...{p=1.0}Я просто хотела узнать, все ли в порядке.")
    call process_character (n, appearance="pose behindhead face curious blush true", text="Э-все было в порядке.")
    call process_character (si, appearance="pose armunder face curious", text="Ты уверен?")

    menu:
        "Спасибо, Мам, но я в порядке.":
            call process_character (n, appearance="pose behindhead face embarrassed blush true")
            call process_character (si, appearance="pose handsfront face neutral", text="Просто хотела убедиться, милый.")
        "Нуу, немного белого вещества появилось через некоторое время.":

            call add_points (si, 1, tag="simone_convo_6_you_sure")

            call process_character (n, appearance="pose behindhead face embarrassed blush true")
            call process_character (si, appearance="pose handsup face neutral", text="Это совершенно нормально, милый.")
            call process_character (si, appearance="pose handsup face neutral", text="Ты кончил.")
            call process_character (n, appearance="pose handpocket face curious", text="К-кончил")
            $ heard_of_ejaculate = True
            call process_character (si, appearance="pose armunder face embarrassed", text="Нуу...")
            $ renpy.pause(2)
            call process_character (si, appearance="pose armunder face embarrassed", text="Так говорят, когда белое вещество выходит.")
            call process_character (si, appearance="pose handsfront face neutral", text="Сначала это может показаться странным, но уверяю, беспокоиться не о чем.")
            call process_character (n, appearance="pose handpocket face concerned blush true")
            $ renpy.pause(1)
            call process_character (n, appearance="pose handpocket face concerned blush true", text="Хорошо.")

    call character_leave_dissolve (n)
    call process_character (si, appearance="pose armunder face concerned", text="(Он явно запутался во всем этом...)")
    $ renpy.pause(1)
    call process_character (si, appearance="pose armunder face concerned", text="(И это звучало так, как будто он был ранен в ванной)")
    call process_character (si, appearance="pose handsup face concerned", text="(Я думала повременить со всеми этими объяснениями)")
    call process_character (si, appearance="pose handsup face concerned", text="(Но я не могу ему сказать не делать этого снова)")
    call process_character (si, appearance="pose handsup face concerned", text="(Надеюсь, он хотя бы научится делать это правильно...)")
    $ renpy.pause(2)
    call process_character (si, appearance="pose armunder face concerned", text="(Но я не уверена, что он сможет сделать это сам...)")

    call process_end_of_conversation ("simone_convo_6", si, default=False, priority=True, considered_scene=True)

    return


label simone_convo_7:
    call process_conversation_beginning ([ (n, "pose handpocket face curious blush true"), (si, "pose handsfront face embarrassed blush true") ])
    call process_character (si, appearance="pose handsfront face embarrassed blush true", text="...")
    call process_character (n, appearance="pose handpocket face curious blush true", text="...")
    call process_character (si, appearance="pose handsfront face embarrassed blush false")
    $ renpy.pause(1)
    call process_character (si, appearance="pose handsfront face embarrassed blush false", text="Ты хорошо отдохнул?")
    call process_character (n, appearance="pose behindhead face concerned blush true", text="Д-да.")
    call process_character (si, appearance="pose handsup face neutral")
    $ si.c("Не расстраивайся из-за того, что случилось, " + n.say_name + ".")
    call process_character (n, appearance="pose handpocket face concerned blush true", text="...")
    call process_character (si, appearance="pose armunder face neutral", text="Сейчас ты приходишь к возрасту, когда всё больше думаешь о девушках.")
    call process_character (si, appearance="pose armunder face neutral", text="Так что не удивительно, когда ты увидел мою...")
    call process_character (si, appearance="pose armunder face embarrassed")
    $ renpy.pause(2)
    call process_character (si, appearance="pose handsfront face neutral", text="Когда ты увидел меня...{p=1.0}Взволновало тебя.")

    menu:
        "Я-я обязательно скажу тебе в следующий раз, прежде чем...":
            call add_points (si, 1, tag="simone_convo_7_excited_you")

            call process_character (n, appearance="pose behindhead face curious blush true")
            call process_character (si, appearance="pose handsfront face neutral", text="Я знаю..")
            call process_character (si, appearance="pose handsup face neutral", text="(Я думаю он в нетерпении \"следующего раза\")")
        "Я хочу видеть твои сиськи, Мам.":

            call add_boldness (1, tag="simone_convo_7_excited_you")

            call process_character (n, appearance="pose behindhead face embarrassed blush true")
            call process_character (si, appearance="pose armunder face embarrassed")
            $ renpy.pause(1)
            call process_character (si, appearance="pose armunder face embarrassed", text="(Это было грубо)")


    call process_character (si, appearance="pose handsup face neutral", text="Тебе надо учиться контролировать себя и держать себя в руках.")
    call process_character (n, appearance="pose handpocket face curious blush true")
    $ renpy.pause(1)
    call process_character (si, appearance="pose handsup face embarrassed", text="(Это неправильно)")
    call process_character (si, appearance="pose handsup face embarrassed", text="(И я все еще думаю о том, сколько он...)")
    $ renpy.pause(2)
    call process_character (si, appearance="pose handsup face embarrassed", text="(Кончил)")
    $ renpy.pause(2)
    call process_character (si, appearance="pose handsfront face concerned blush true", text="Мы не должны говорить об этом здесь.")
    call process_character (n, appearance="pose handpocket face concerned blush false", text="...")
    call process_character (si, appearance="pose armunder face neutral blush true", text="Х-хочешь что-нибудь поесть?")

    call process_end_of_conversation ("simone_convo_7", si, default=False, priority=True, considered_scene=True)

    return

label simone_convo_8:
    call process_conversation_beginning ([ (n, ""), (si, "pose handsup face neutral") ])
    call process_character (si, appearance="pose handsup face happy", text="Ты такой бескорыстный, [n.say_name]!")
    call process_character (n, appearance="pose handpocket face neutral", text="Что?")
    call process_character (si, appearance="pose armunder face neutral", text="Ты даёшь [k.say_name] брать твой ноутбук.")
    call process_character (n, appearance="pose behindhead face neutral", text="В этом не было ничего особенного.")
    call process_character (si, appearance="pose handsfront face neutral", text="Я надеюсь [k.say_name] отблагодарила тебя.")
    call process_character (n, appearance="pose behindhead face neutral", text="Да, отблагодарила.")
    call process_character (si, appearance="pose handsfront face neutral", text="Это хорошо.")
    call process_character (si, appearance="pose handsup face concerned", text="Твоей сестре иногда трудно оценить щедрость других.")
    call process_character (si, appearance="pose handsup face neutral", text="Я рада, что она совершенствуется.")
    call process_character (n, appearance="pose handpocket face curious", text="Она говорила тебе, что случилось с ее компьютером?")
    call process_character (si, appearance="pose armunder face concerned", text="{i}Эхх{/i}...")
    call process_character (si, appearance="pose armunder face concerned", text="Да...")
    call process_character (si, appearance="pose armunder face concerned", text="Но перед этим она долго отмазывалась.")
    call process_character (n, appearance="pose behindhead face concerned", text="Ты на неё разозлилась?")
    call process_character (si, appearance="pose handsfront face neutral", text="Как только я узнала, что на самом деле произошло, сразу простила.")
    call process_character (si, appearance="pose handsfront face neutral", text="Как только я узнала, что на самом деле произошло, нет, это не так.")
    call process_character (si, appearance="pose armunder face neutral", text="Твоя сестра многого добилась.")
    call process_character (si, appearance="pose armunder face neutral", text="Но ей надо повзрослеть.")

    call process_end_of_conversation ("simone_convo_8", si, default=False, priority=False)

    return

label simone_convo_9:
    call process_conversation_beginning ([ (n, ""), (si, "pose armunder face neutral") ])
    call process_character (si, appearance="pose armunder face neutral", text="Я благодарна моей компании, что она позволила мне работать дома.")
    call process_character (si, appearance="pose handsup face neutral", text="Мне нравится работать дома.")
    call process_character (n, appearance="pose handpocket face curious", text="Почему?")
    call process_character (si, appearance="pose handsfront face neutral", text="Я могу проводить больше времени с тобой, [sa.say_name], и [k.say_name].")
    call process_character (si, appearance="pose handsfront face neutral", text="Также я бы не хотела, чтобы ты и [sa.say_name] были одни весь день, пока [k.say_name] на работе.")
    call process_character (n, appearance="pose behindhead face neutral", text="[sa.say_name] и я сможем и одни управиться с домом.")
    call process_character (n, appearance="pose behindhead face neutral", text="Мы бы просто играли в видеоигры весь день!")
    call process_character (n, appearance="pose handpocket face neutral")
    call process_character (si, appearance="pose armunder face happy", text="Кто бы сомневался!")
    call process_character (si, appearance="pose handsup face curious", text="Я еще не знаю этот район.")
    call process_character (si, appearance="pose handsup face curious", text="Лучше быть в безопасности, чем потом сожалеть.")
    call process_character (n, appearance="pose handpocket face concerned", text="Думаешь, этот район плохой?")
    call process_character (si, appearance="pose handsup face neutral", text="Я думаю, что он безопаснее, чем другие.")
    call process_character (si, appearance="pose armunder face neutral", text="Доверяй, но проверяй.")

    call process_end_of_conversation ("simone_convo_9", si, default=False, priority=False)

    return

label simone_convo_10:
    call process_conversation_beginning ([ (n, "pose twohandfist face neutral"), (si, "pose handsfront") ])
    call process_character (n, appearance="pose twohandfist face neutral", text="Ты пойдешь в бассейн, мама?")
    call process_character (si, appearance="pose armunder face neutral", text="Наверное нет, дорогой.")
    call process_character (n, appearance="pose behindhead face concerned", text="А почему бы и нет?")
    call process_character (si, appearance="pose handsfront face neutral", text="Это трудно объяснить.")
    call process_character (si, appearance="pose handsfront face neutral", text="Но если я пойду поплавать.....")
    call process_character (si, appearance="pose handsfront face neutral", text="Это значит, что я должна надеть купальник.")
    call process_character (si, appearance="pose handsfront face neutral", text="А мне некомфортно в нём")
    call process_character (n, appearance="pose handpocket face concerned", text="Почему?")
    call process_character (si, appearance="pose armunder face neutral", text="Некоторые женщины [n.say_name] очень застенчивы.")
    call process_character (si, appearance="pose armunder face neutral", text="Это значит, что мы заботимся о том, как мы выглядим.")
    call process_character (si, appearance="pose armunder face neutral", text="И что другие будут думать, о нас.")
    call process_character (n, appearance="pose behindhead face curious", text="...")
    call process_character (n, appearance="pose behindhead face curious", text="Не думаю, что понимаю это.")
    call process_character (si, appearance="pose handsfront face neutral", text="Я не могу надеть купальник.")
    call process_character (si, appearance="pose handsfront face neutral", text="Я бы слишком беспокоилась о том, как выгляжу.")
    call process_character (n, appearance="pose handpocket face concerned", text="А, понятно...")
    pause 0.5
    call process_character (n, appearance="pose handpocket face neutral", text="Это очень плохо, мама.")
    call process_character (n, appearance="pose handpocket face neutral", text="Уверен, тебе понравится бассейн!")
    call process_character (si, appearance="pose handsup face neutral", text="Не беспокойся [n.say_name].")
    call process_character (si, appearance="pose handsup face neutral", text="Сходи один.")
    call process_character (si, appearance="pose handsup face happy", text="Мой сад продолжает меня развлекать!")

    call process_end_of_conversation ("simone_convo_10", si, default=False, priority=False)

    return

label simone_convo_11:
    call process_conversation_beginning ([(si, "pose handsup face neutral blush false"), (n, "pose handpocket face neutral blush false")])
    call process_character (si, appearance="pose handsup face neutral blush false", text="Парк в этом городе прекрасен.")
    call process_character (n, appearance="pose twohandfist face neutral blush false", text="О да, Мама")
    call process_character (n, appearance="pose twohandfist face neutral blush false", text="Я недавно туда ходил!")
    call process_character (si, appearance="pose handsfront face neutral blush false", text="О, правда?")
    call process_character (si, appearance="pose handsfront face neutral blush false", text="Что тебе там понравилось?")
    call process_character (n, appearance="pose handpocket face neutral blush false", text="Ну, там есть тропинки, которые идут под кроной деревьев.")
    call process_character (n, appearance="pose handpocket face neutral blush false", text="И есть место, где куча цветов!")
    call process_character (si, appearance="pose armunder face happy blush false", text="Надо обязательно это увидеть самой!")
    call process_character (si, appearance="pose armunder face happy blush false", text="Может быть, у меня будут цветочные идеи для моего сада.")
    call process_character (n, appearance="pose behindhead face neutral blush false", text="Я хотел спросить, как поживает твой сад, Мам?")
    call process_character (si, appearance="pose handsfront face neutral blush false", text="Думаю, хорошо")
    call process_character (si, appearance="pose handsfront face neutral blush false", text="Наш двор получает много солнца, так что это не проблема.")
    call process_character (si, appearance="pose armunder face neutral blush false", text="Но растениям постоянно нужна вода.")
    call process_character (si, appearance="pose armunder face neutral blush false", text="Они быстро высыхают под солнцем.")
    call process_character (n, appearance="pose twohandfist face neutral blush false", text="Думаешь, сад нас прокормит?")
    call process_character (si, appearance="pose armunder face happy blush false", text="Это пока маленький сад, милый!")
    call process_character (si, appearance="pose armunder face happy blush false", text="Пройдет некоторое время, прежде чем он накормит всех нас!")
    call process_character (n, appearance="pose handpocket face neutral blush false")
    call process_character (si, appearance="pose handsup face neutral blush false", text="Но я рада сообщить, что первые овощи, которые я выращиваю, выглядят здоровыми!")
    call process_character (n, appearance="pose handfist face happy blush false", text="Мило! Какие это овощи?")
    call process_character (si, appearance="pose handsfront face neutral blush false", text="Можно сказать, это овощи для \"чайников\".")
    call process_character (si, appearance="pose handsfront face neutral blush false", text="Помидоры и салат.")
    call process_character (si, appearance="pose armunder face happy blush false", text="Необходимые компоненты для салата!")
    call process_character (n, appearance="pose handpocket face neutral blush false", text="[k.say_name] это одобрит.")
    call process_character (si, appearance="pose handsfront face neutral blush false", text="Да, я знаю, что ты не очень любишь салат.")
    call process_character (si, appearance="pose handsup face neutral blush false", text="Может быть, попробовать вырастить фрукты.")
    call process_character (n, appearance="pose twohandfist face neutral blush false", text="Чернику?!")
    call process_character (si, appearance="pose handsfront face happy blush false", text="Хаха, ну посмотрим.")

    call process_end_of_conversation ("simone_convo_11", si, default=False, priority=False)

    return


label simone_convo_12:

    if week.time == "night":
        call process_conversation_beginning ([(n, "pose handpocket face neutral blush false"), (si, "outfit nightgown pose handsfront face neutral blush false")])
        call process_character (n, appearance="pose handpocket face neutral blush false", text="Привет, Мам.")
        call process_character (n, appearance="pose handpocket face neutral blush false", text="Ты уже в ночной рубашке?")
        call process_character (si, appearance="pose handsfront face neutral blush false", text="Я плохо спала прошлой ночью.")
        call process_character (si, appearance="pose handsfront face neutral blush false", text="Так что я хожу целый день уставшей.")
        call process_character (si, appearance="pose handsup face neutral blush false", text="Я подумала лечь спать пораньше, чтобы лучше отдохнуть.")
    else:
        call process_conversation_beginning ([(n, "pose handpocket face neutral blush false"), (si, "outfit clothes pose handsfront face happy blush false")])
        call process_character (si, appearance="pose handsfront face happy blush false", text="{i}Зевает{/i}...")
        call process_character (n, appearance="pose handpocket face neutral blush false", text="Привет, Мам.")
        call process_character (n, appearance="pose handpocket face neutral blush false", text="Ты выглядишь уставшей..")
        call process_character (si, appearance="pose armunder face happy blush false", text="Ха-ха, что меня выдало?")
        call process_character (si, appearance="pose armunder face neutral blush false", text="Мне пришлось работать допоздна.")
        call process_character (si, appearance="pose armunder face neutral blush false", text="Потеряла счет времени.")


    call process_character (n, appearance="pose handpocket face curious blush false", text="...")
    call process_character (n, appearance="pose handpocket face curious blush false", text="(Мама не говорит о том, что я подглядывал за ней)")
    call process_character (n, appearance="pose handpocket face curious blush false", text="...")
    call process_character (n, appearance="pose handpocket face curious blush false", text="(Может быть, она забыла об этом?)")
    call process_character (si, appearance="pose handsfront face concerned blush false", text="...")
    call process_character (si, appearance="pose handsfront face concerned blush false", text="(Не похоже, что [n.say_name] хочет признаться)")
    call process_character (si, appearance="pose handsup face concerned blush false", text="[n.say_name]?")
    call process_character (si, appearance="pose handsup face concerned blush false", text="Ты хочешь мне что-то сказать?")
    call process_character (n, appearance="pose handpocket face concerned blush true", text="{i}Сглатывает{/i}...")
    call process_character (n, appearance="pose handpocket face concerned blush true", text="(Нет, она не забыла)")
    call process_character (si, appearance="pose armunder face concerned blush false", text="(Он знает, о чем я хотел поговорить)")
    call process_character (si, appearance="pose armunder face concerned blush false", text="[n.say_name]...")
    call process_character (si, appearance="pose armunder face concerned blush false", text="Почему ты подглядывал за мной?")
    call process_character (n, appearance="pose behindhead face embarrassed blush true", text="Нуу...")
    call process_character (n, appearance="pose behindhead face embarrassed blush true", text="Я-я, потому что...")
    call process_character (n, appearance="pose behindhead face embarrassed blush true", text="...")
    call process_character (si, appearance="pose handsfront face concerned blush false", text="Что ты там делал [n.say_name]?")
    call process_character (si, appearance="pose handsfront face concerned blush false", text="Расскажи мне всю правду...")
    call process_character (n, appearance="pose behindhead face embarrassed blush true", text="Я-я...")
    call process_character (n, appearance="pose behindhead face embarrassed blush true", text="...{p}...")
    call process_character (n, appearance="pose twohandfist face embarrassed blush true", text="Я мастурбировал, Мама!!")

    call process_character (si, appearance="pose handsup face concerned blush false")
    pause 1.0
    call process_character (si, appearance="pose handsup face concerned blush false", text="Почему ты мастурбировал?")

    call process_character (n, appearance="pose twohandfist face embarrassed blush true", text="Я мастурбировал, потому что...")
    call process_character (n, appearance="pose twohandfist face embarrassed blush true", text="Я... Я был возбуждён.")
    call process_character (si, appearance="pose armunder face concerned blush false", text="Почему ты был возбуждён [n.say_name]?")
    call process_character (n, appearance="pose behindhead face concerned blush true", text="Я... Я...")
    call process_character (n, appearance="pose behindhead face concerned blush true", text="Я не знаю.")
    call process_character (si, appearance="pose handsup face concerned blush false", text="Я думаю ты знаешь, [n.say_name].")
    call process_character (si, appearance="pose handsup face concerned blush false", text="Пожалуйста, скажи мне.")
    call process_character (n, appearance="pose behindhead face concerned blush true", text="...")
    call process_character (n, appearance="pose behindhead face concerned blush true", text="П-причина, по которой я возбудился и начал мастурбировать, была...")
    call process_character (n, appearance="pose behindhead face concerned blush true", text="...")
    call process_character (n, appearance="pose twohandfist face embarrassed blush true", text="М-мне нравится смотреть на тебя.")
    call process_character (n, appearance="pose twohandfist face embarrassed blush true", text="Я-я начал мастурбировать и {w=1.0}Не мог остановиться!")
    call process_character (n, appearance="pose twohandfist face embarrassed blush true", text="Мне было очень хорошо!")
    call process_character (si, appearance="pose armunder face embarrassed blush false", text="...")
    call process_character (si, appearance="pose armunder face embarrassed blush false", text="(Так что, он мастурбирует не только на мою грудь)")
    call process_character (si, appearance="pose armunder face embarrassed blush false", text="(Ему этого мало)")
    call process_character (si, appearance="pose armunder face embarrassed blush false", text="(Теперь ему нравится смотреть на другие части моего тела...)")
    call process_character (si, appearance="pose armunder face embarrassed blush false", text="...")
    call process_character (si, appearance="pose handsfront face concerned blush false", text="Понятно...")
    call process_character (n, appearance="pose handpocket face concerned blush true", text="...")
    call process_character (si, appearance="pose armunder face concerned blush false", text="Ну, тебе не следовало шпионить за мной, [n.say_name].")
    call process_character (si, appearance="pose armunder face concerned blush false", text="Ты же знаешь, что лучше не делать что-то подобное.")
    call process_character (n, appearance="pose twohandfist face concerned blush true", text="Прости, Мама!")
    call process_character (n, appearance="pose twohandfist face concerned blush true", text="Я знал, что это неправильно, и я должен был остановиться!")
    call process_character (n, appearance="pose twohandfist face concerned blush true", text="Мне действительно очень жаль!")
    call process_character (si, appearance="pose handsup face concerned blush false", text="...")
    call process_character (si, appearance="pose handsup face neutral blush false", text="Я знаю, ты переживаешь из-за этого.")
    call process_character (si, appearance="pose handsup face neutral blush false", text="И что сказал правду, [n.say_name].")
    call process_character (n, appearance="pose behindhead face concerned blush true", text="Ты ведь больше не злишься на меня, правда Мама?")
    call process_character (si, appearance="pose armunder face neutral blush false", text="Конечно, нет дорогой.")
    call process_character (si, appearance="pose armunder face neutral blush false", text="Ты признался, и понял, что поступил неправильно.")
    call process_character (si, appearance="pose armunder face neutral blush false", text="Хорошо, что ты понял, что совершил ошибку.")
    call process_character (n, appearance="pose behindhead face concerned blush false", text="...")
    call process_character (n, appearance="pose behindhead face concerned blush false", text="М-Мам?")
    call process_character (n, appearance="pose behindhead face concerned blush false", text="...")
    call process_character (n, appearance="pose behindhead face concerned blush false", text="Ничего, если я задам тебе вопрос, что ты делала?")
    call process_character (si, appearance="pose handsfront face neutral blush false", text="...")
    call process_character (si, appearance="pose handsfront face neutral blush false", text="Нуу...")
    call process_character (si, appearance="pose handsfront face neutral blush false", text="Это нормально, [n.say_name].")
    call process_character (si, appearance="pose handsfront face neutral blush false", text="Что ты хочешь знать?")

    menu:
        "Ты мастурбировала?":
            call process_character (si, appearance="pose armunder face neutral blush true", text="...")
            call process_character (si, appearance="pose armunder face neutral blush true", text="Да...")
            call process_character (si, appearance="pose armunder face neutral blush true", text="Я мастурбировала.")
        "О чем ты думала, когда я тебя увидел?":
            call add_boldness (1, tag="simone_convo_12_thinking_about")
            call process_character (si, appearance="pose armunder face embarrassed blush true", text="!")
            call process_character (si, appearance="pose armunder face embarrassed blush true", text="...")
            call process_character (si, appearance="pose armunder face embarrassed blush true", text="(Было бы нормальным сказать правду [n.say_name], но...)")
            call process_character (si, appearance="pose armunder face embarrassed blush true", text="(Рассказать ему о чём я фантазировала...)")
            call process_character (si, appearance="pose armunder face embarrassed blush true", text="(Это приведет к неловкой ситуации!)")
            call process_character (si, appearance="pose armunder face embarrassed blush true", text="...{p}...")
            call process_character (si, appearance="pose handsup face neutral blush false", text="(Я лучше {w=1.0}схитрю...)")
            call process_character (si, appearance="pose handsup face neutral blush false", text="Нуу...")
            call process_character (si, appearance="pose handsup face neutral blush false", text="Мама думала о том, как это приятно.")

    call process_character (n, appearance="pose behindhead face curious blush false", text="К-как...")
    call process_character (n, appearance="pose behindhead face curious blush false", text="Это приятное чувство?")
    call process_character (si, appearance="pose handsfront face neutral blush false", text="Да, очень приятное.")
    call process_character (si, appearance="pose handsfront face neutral blush false", text="Это как чувствовать, когда мастурбируешь.")
    call process_character (n, appearance="pose handpocket face concerned blush false", text="М-мам?")
    call process_character (n, appearance="pose handpocket face concerned blush false", text="...")
    call process_character (n, appearance="pose handpocket face concerned blush false", text="Это плохо, что я думаю о тебе, когда мастурбирую?")
    call process_character (si, appearance="pose armunder face embarrassed blush true", text="...")
    call process_character (si, appearance="pose armunder face embarrassed blush true", text="(Что я должна ему сказать?)")
    call process_character (si, appearance="pose armunder face embarrassed blush true", text="...")
    call process_character (si, appearance="pose armunder face embarrassed blush true", text="(Если я скажу, что это плохо, то он будет чувствовать себя виноватым каждый раз, когда он мастурбирует)")
    call process_character (si, appearance="pose armunder face embarrassed blush true", text="(Но если я скажу, что все в порядке...)")
    call process_character (si, appearance="pose armunder face embarrassed blush true", text="(Что мне ответить?)")
    call process_character (si, appearance="pose armunder face embarrassed blush true", text="(Он станет более любопытным?)")
    call process_character (si, appearance="pose armunder face embarrassed blush true", text="...")
    call process_character (si, appearance="pose armunder face embarrassed blush true", text="(И не узнать, как он отреагирует)")
    call process_character (si, appearance="pose armunder face embarrassed blush true", text="...{p}...")
    call process_character (si, appearance="pose armunder face neutral blush true", text="Я...")
    call process_character (si, appearance="pose armunder face neutral blush true", text="У меня нет проблем с этим [n.say_name].")
    call process_character (n, appearance="pose handpocket face neutral blush false", text="З-значит, все в порядке?")
    call process_character (si, appearance="pose handsup face neutral blush false", text="Это совершенно нормально.")
    call process_character (n, appearance="pose twohandfist face neutral blush false", text="Боже мой, Мама, спасибо!")
    call process_character (n, appearance="pose twohandfist face neutral blush false", text="Я чувствую себя намного лучше, зная, что все в порядке!")
    call process_character (n, appearance="pose twohandfist face neutral blush false", text="Я очень сильно беспокоился об этом.")
    call process_character (si, appearance="pose handsfront face neutral blush false", text="Не о чем беспокоиться, [n.say_name].")
    call process_character (si, appearance="pose handsfront face neutral blush false", text="Я рада, что ты чувствуешь себя лучше.")
    call process_character (n, appearance="pose handpocket face happy blush false", text="Еще раз спасибо, Мам!")
    call process_character (n, appearance="pose handpocket face happy blush false", text="Люблю тебя!")
    call process_character (si, appearance="pose armunder face neutral blush false", text="И я тебя тоже, [n.say_name].")

    call character_leave_dissolve (n)
    $ renpy.pause(1)

    call process_character (si, appearance="pose handsfront face neutral blush false", text="...")
    call process_character (si, appearance="pose armunder face neutral blush false", text="(Я рада, что он чувствует себя лучше)")
    call process_character (si, appearance="pose armunder face neutral blush false", text="...")
    call process_character (si, appearance="pose armunder face neutral blush true", text="(Интересно, что он представляет обо мне?)")
    call process_character (si, appearance="pose armunder face neutral blush false", text="...")
    call process_character (si, appearance="pose armunder face neutral blush false", text="(Они такие же, как и мои фантазии?)")

    call process_end_of_conversation ("simone_convo_12", si, default=False, priority=True, considered_scene=True)

    return


label simone_convo_13:

    call process_conversation_beginning ([(si, "pose armunder face happy blush false"), (n, "pose handpocket face neutral blush false")])
    call process_character (si, appearance="pose armunder face happy blush false", text="Мои руки свинцовые!")
    call process_character (n, appearance="outfit clothesjacket pose handpocket face neutral blush false", text="О, это всё из-за работы в саду?")
    call process_character (si, appearance="pose handsfront face neutral blush false", text="Да.")
    call process_character (si, appearance="pose handsfront face neutral blush false", text="А как на счёт тебя?")
    call process_character (n, appearance="pose handfist face neutral blush false", text="Мне немного больно, но не слишком.")
    call process_character (si, appearance="pose handsfront face happy blush false", text="Это потому, что у вас новые, хорошо смазанные детали!")
    call process_character (si, appearance="pose handsfront face happy blush false", text="А я уже с пробегом!")
    call process_character (n, appearance="pose handpocket face curious blush false", text="...")
    call process_character (si, appearance="pose handsup face happy blush false", text="Это означает, что я старею, [n.say_name].")
    call process_character (n, appearance="pose twohandfist face concerned blush false", text="Ты не старая, Мамочка!")
    call process_character (si, appearance="pose handsfront face neutral blush false")
    call process_character (n, appearance="pose behindhead face concerned blush false", text="Вернее, ты не выглядишь старой...")
    call process_character (si, appearance="pose armunder face neutral blush false", text="Ты учишься, как очаровать зрелую женщину [n.say_name]?")
    call process_character (si, appearance="pose armunder face happy blush false", text="Потому что это сработало на мне!")
    call process_character (n, appearance="pose behindhead face neutral blush false", text="Эмм, я так не думаю.")
    call process_character (si, appearance="pose armunder face neutral blush false", text="...")
    call process_character (si, appearance="pose armunder face neutral blush false", text="Я хочу спросить у тебя, [n.say_name].")
    call process_character (n, appearance="pose handpocket face neutral blush false", text="Что?")
    call process_character (si, appearance="pose armunder face neutral blush false", text="Я знаю, что ты, наверное, не думаешь об этом, но...")
    call process_character (si, appearance="pose handsfront face neutral blush false", text="С какой девушкой ты бы хотел встречаться?")
    call process_character (si, appearance="pose handsfront face neutral blush false", text="Если ты конечно хочешь встречаться.")
    call process_character (n, appearance="pose behindhead face curious blush false", text="...")
    call process_character (n, appearance="pose behindhead face curious blush false", text="Я не встречаюсь с девушками...")
    call process_character (si, appearance="pose handsfront face neutral blush false", text="Ну, просто гипотетически.")
    call process_character (si, appearance="pose handsfront face neutral blush false", text="Притворись, что хочешь встречаться.")
    call process_character (si, appearance="pose armunder face neutral blush false", text="С какой женщиной ты бы хотел встречаться?")
    call process_character (n, appearance="pose handpocket face curious blush false", text="Хмм...")
    call process_character (n, appearance="pose handpocket face curious blush false", text="Какой?")
    call process_character (si, appearance="pose handsup face neutral blush false", text="Например...")
    call process_character (si, appearance="pose handsup face neutral blush false", text="...")
    call process_character (si, appearance="pose handsup face flirt blush false", text="Хотел бы ты пойти на свидание с женщиной моего возраста?")

    menu:
        "Определенно!":
            call process_character (n, appearance="pose handfist face happy blush false")
            call process_character (si, appearance="pose handsfront face neutral blush false", text="Спасибо, [n.say_name]!")
            call process_character (si, appearance="pose handsfront face neutral blush false", text="Так ты не против встречаться с женщиной постарше?")
            call process_character (n, appearance="pose twohandfist face neutral blush false", text="Вовсе нет!")
            call process_character (n, appearance="pose twohandfist face neutral blush false", text="Особенно, если они бы были такими же милыми, как мама!")
            call process_character (si, appearance="pose armunder face flirt blush false", text="Ты становишься настоящим дамским угодником.")
        "Как насчет того, чтобы быть моей девушкой?":
            call add_boldness (1, tag="simone_convo_13_being_my_girlfriend")

            call process_character (si, appearance="pose armunder face happy blush true", text="Хаха!")
            call process_character (si, appearance="pose armunder face happy blush true", text="И первого свидания не будет?")
            call process_character (si, appearance="pose armunder face happy blush true", text="Просто перейти сразу к делу и быть в отношениях?")
            call process_character (n, appearance="pose behindhead face curious blush false", text="Я не должен этого делать?")
            call process_character (si, appearance="pose handsfront face neutral blush false", text="Я имею в виду, ты можешь попробовать.")
            call process_character (si, appearance="pose armunder face neutral blush false", text="Но, как правило, первое свидание позволит вам знать, если у вас есть связь с человеком.")
            call process_character (si, appearance="pose armunder face neutral blush false", text="Это отправная точка для начала отношений.")
            call process_character (n, appearance="pose handpocket face happy blush false", text="Охх...")
            call process_character (n, appearance="pose handpocket face happy blush false", text="Я понял..")
            call process_character (si, appearance="pose handsfront face flirt blush true", text="(Быть его девушкой?)")
            call process_character (n, appearance="pose handpocket face neutral blush false")
            call process_character (si, appearance="pose armunder face flirt blush true", text="(Ну, я не думаю, что слишком много людей будут обеспокоены разницей в возрасте)")
            call process_character (si, appearance="pose armunder face embarrassed blush true", text="(Но им придется привыкнуть к отношениям матери и сына на {i}таком{/i} уровне...)")
            call process_character (si, appearance="pose armunder face embarrassed blush true", text="...")

    call process_character (si, appearance="pose handsfront face neutral blush false", text="Мне было просто любопытно...")
    call process_character (si, appearance="pose handsfront face neutral blush false", text="Не нужно слишком много думать об этом.")
    call process_character (n, appearance="pose handpocket face neutral blush false", text="...")
    call process_character (n, appearance="pose behindhead face neutral blush false", text="Когда ты снова будешь работать в саду?")
    call process_character (si, appearance="pose handsup face neutral blush false", text="Да каждый день.")
    call process_character (si, appearance="pose handsup face neutral blush false", text="Но сейчас я собираюсь отдохнуть.")
    call process_character (n, appearance="pose behindhead face curious blush false", text="...")
    call process_character (n, appearance="pose behindhead face curious blush false", text="Это значит, что ты не сможешь...")
    call process_character (n, appearance="pose behindhead face curious blush false", text="Потрогать мой пенис сегодня?")
    call process_character (si, appearance="pose handsup face neutral blush false", text="...")
    call process_character (si, appearance="pose armunder face neutral blush false", text="([k.say_name] и [sa.say_name] здесь.)")
    call process_character (si, appearance="pose armunder face embarrassed blush false", text="(Не совсем умно было бы ласкать [n.say_name] и рисковать быть замеченной..)")
    call process_character (si, appearance="pose armunder face embarrassed blush false", text="...")
    call process_character (si, appearance="pose handsfront face neutral blush false", text="Извини, [n.say_name], я не думаю, что сегодня стоит это делать.")
    call process_character (n, appearance="pose handpocket face concerned blush false", text="Охх...")
    call process_character (si, appearance="pose armunder face neutral blush false", text="Но...")
    call process_character (si, appearance="pose armunder face neutral blush false", text="Я знаю, тебе это нравится.")
    call process_character (si, appearance="pose armunder face neutral blush false", text="...")
    call process_character (si, appearance="pose handsfront face neutral blush false", text="Так что всегда можешь спросить меня, когда я свободна.")
    call process_character (n, appearance="pose twohandfist face happy blush false", text="Круто!")
    call process_character (si, appearance="pose armunder face curious blush false", text="...")
    call process_character (si, appearance="pose armunder face curious blush false", text="(Возможно, я смогу найти способ убедить [k.say_name] и [sa.say_name] пойти в торговый центр)")
    call process_character (si, appearance="pose armunder face flirt blush false", text="(Тогда у нас будет достаточно времени...)")

    call process_end_of_conversation ("simone_convo_13", si, default=False, priority=True, considered_scene=True)

    return


label simone_convo_14:
    call process_conversation_beginning ([(si, "outfit clothes pose handsfront face neutral blush false"), (n, "outfit clothesjacket pose handpocket face neutral blush false")])
    call process_character (si, appearance="outfit clothes pose handsup face happy blush false", text="Я никогда не видела дом таким прибранным! ")
    call process_character (n, appearance="outfit clothesjacket pose handpocket face neutral blush false", text="Ты выглядишь очень счастливой из-за этого, Мама.")
    call process_character (si, appearance="pose handsfront face neutral blush false", text="У меня наконец-то есть свободное время.")
    call process_character (si, appearance="pose handsfront face happy blush false", text="В первый раз!")
    call process_character (n, appearance="pose handfist face happy blush false", text="Здорово!")
    call process_character (n, appearance="pose handfist face happy blush false", text="Чем планируешь заняться?")
    call process_character (si, appearance="pose armunder face neutral blush false", text="Знаешь, это хороший вопрос!")
    call process_character (si, appearance="pose armunder face neutral blush false", text="Мне нужно подумать об этом...")
    call process_character (n, appearance="pose twohandfist face neutral blush false", text="Ты можешь поплавать в бассейне!")
    call process_character (si, appearance="pose handsfront face neutral blush false", text="У меня еще не было возможности, это правда.")
    call process_character (si, appearance="pose handsfront face neutral blush false", text="...")
    call process_character (si, appearance="pose armunder face happy blush false", text="Знаешь, я думаю, что сделаю это!")
    call process_character (n, appearance="pose handpocket face neutral blush false", text="Бассейн - отличная идея!")
    call process_character (si, appearance="pose handsup face neutral blush false", text="Пойду переоденусь в купальник прямо сейчас.")
    call process_character (n, appearance="pose handpocket face neutral blush false", text="...")
    call process_character (n, appearance="pose behindhead face neutral blush false", text="Мам?")
    call process_character (n, appearance="pose behindhead face neutral blush false", text="Ничего, если я посмотрю, как ты переодеваешься?")
    call process_character (si, appearance="pose handsfront face happy blush false", text="Это то, что ты хочешь увидеть?")
    call process_character (si, appearance="pose handsfront face happy blush false", text="На то, как я раздеваюсь вместо того, чтобы идти в бассейн?")
    call process_character (n, appearance="pose behindhead face neutral blush false", text="...")
    call process_character (n, appearance="pose behindhead face neutral blush false", text="И то, и другое.")
    call process_character (si, appearance="pose handsup face neutral blush false")
    $ renpy.pause(0.5)
    call character_leave_dissolve (si)
    $ renpy.pause(1)

    call process_character (si, appearance="outfit underwear pose handsup face flirt blush false", text="Ты уж выбери, [n.say_name].")
    call process_character (si, appearance="pose handsup face flirt blush false", text="Что мне снять сначала, лифчик или трусики?")

    menu:
        "Я хочу увидеть твои сиськи, Мама!":
            call character_leave_dissolve (si)
            $ renpy.pause(1)
            call process_character (si, appearance="outfit topless_underwear pose handsfront face happy blush false", text="Вот они, только для тебя!")
            call process_character (n, appearance="outfit clothesjacket_hard pose neutral face aroused blush true", text="...{p}...")
            call process_character (si, appearance="pose armunder face flirt blush false", text="...")
            call process_character (si, appearance="pose armunder face neutral blush false", text="(Я надеюсь, что он будет немного более сдержан, глядя на грудь женщины)")
            call process_character (si, appearance="pose armunder face neutral blush false", text="(А то с таким взглядом его за километр будет видно...)")
            call process_character (si, appearance="pose armunder face neutral blush false", text="...")
            call process_character (si, appearance="pose handsfront face neutral blush false", text="Теперь я сниму трусики.")
        "Я хочу увидеть твою вагину, Мама!":
            call character_leave_dissolve (si)
            $ renpy.pause(1)
            call process_character (si, appearance="outfit underwear_bottomless pose handsup face flirt blush false")
            $ renpy.pause(1)

            call process_character (si, appearance="outfit underwear_bottomless pose handsup face flirt blush false", text="Она также называется киска, пизда, или бобрятинка.")
            call process_character (n, appearance="pose behindhead face happy blush true", text="Бобрятинка?")
            call process_character (si, appearance="pose armunder face neutral blush false", text="Я знаю, это смешное название.")
            call process_character (si, appearance="pose armunder face neutral blush false", text="Используется, когда у женщины много волос вокруг промежности.")
            call process_character (n, appearance="pose handpocket face neutral blush true", text="Как у тебя, Мам?")
            call process_character (si, appearance="pose handsup face happy blush false", text="Надеюсь, я там не слишком волосатая!")
            call process_character (n, appearance="outfit clothesjacket_hard pose twohandfist face aroused blush true", text="Мне нравится, Мама.")
            call process_character (si, appearance="pose armunder face flirt blush false", text="(Я думаю, ему просто нравится видеть меня голой)")
            call process_character (si, appearance="pose armunder face flirt blush false", text="...")
            call process_character (si, appearance="pose handsfront face neutral blush false", text="Позволь мне снять лифчик.")

    call character_leave_dissolve (si)
    $ renpy.pause(1)
    call process_character (si, appearance="outfit nude")
    call process_character (n, appearance="pose behindhead face flirty blush true")
    call process_character (si, appearance="pose armunder face flirt blush false", text="Тебе надо несколько минут, [n.say_name]?")
    call process_character (n, appearance="pose behindhead face aroused blush true", text="...")
    call process_character (n, appearance="pose handpocket face aroused blush true", text="Я бы хотел, чтобы ты все время была голой, Мама.")
    call process_character (si, appearance="pose handsup face flirt blush true", text="[n.say_name]! Шалун!")
    call process_character (si, appearance="pose armunder face flirt blush true", text="Ты хочешь, чтобы твоя мама ходила голой все время?")
    call process_character (n, appearance="pose behindhead face curious blush true", text="Это было бы замечательно.")
    call process_character (si, appearance="pose handsup face happy blush true", text="Хаха, [n.say_name]!")
    call process_character (si, appearance="pose handsup face happy blush true", text="Какой шалун!")
    call process_character (n, appearance="pose handpocket face neutral blush false")

    call character_leave_dissolve (si)
    $ renpy.pause(1)

    call process_character (si, appearance="outfit swimsuit pose handsfront face neutral blush false", text="Ты присоединишься ко мне, [n.say_name]?")
    call process_character (n, appearance="pose twohandfist face neutral blush false", text="О, да!")
    call process_character (n, appearance="pose twohandfist face neutral blush false", text="Я никогда не отказываюсь от бассейна!")
    call process_character (si, appearance="pose handsup face neutral blush false", text="Просто будь осторожен надевая одежду, когда у тебя эрекция.")
    call process_character (n, appearance="pose behindhead face embarrassed blush true", text="...")

    call process_end_of_conversation ("simone_convo_14", si, default=False, priority=True, considered_scene=True)

    return


label simone_convo_15:
    call process_conversation_beginning ([(si, "pose handsfront face neutral blush false"), (n, "pose handpocket face neutral blush false")])

    call process_character (si, appearance="pose handsfront face neutral blush false", text="Привет, милый.")
    call process_character (n, appearance="pose handpocket face neutral blush false", text="Привет, Мам.")
    call process_character (si, appearance="pose armunder face neutral blush false", text="Где [sa.say_name]?")

    if store.had_julia_arrived_scene and "julia_scene_post_vaginal" not in scenes_completed:
        call process_character (n, appearance="pose handpocket face neutral blush false", text="Она и [julia.say_name] просматривают коллекцию видеоигр в её комнате.")
        call process_character (n, appearance="pose behindhead face neutral blush false", text="Я думаю, что она также планирует сыграть в Храмы и Гидры.")
        call process_character (si, appearance="pose armunder face happy blush false", text="Надеюсь, у нее всё получится!")
        call process_character (si, appearance="pose armunder face neutral blush false", text="[julia.say_name] любит играть с вами двумя..")
        call process_character (si, appearance="pose handsup face neutral blush false", text="Ты присоединишься к ним?")
        call process_character (n, appearance="pose handfist face neutral blush false", text="Через некоторое время, да!")
        call process_character (n, appearance="pose handfist face neutral blush false", text="[sa.say_name] должна сначала повторить правила [julia.say_name], потому что она забыла.")
        call process_character (si, appearance="pose handsup face neutral blush false", text="А, понятно..")
        call process_character (si, appearance="pose handsup face happy blush false", text="Мой мозг плавится, пытаясь прочитать правила [sa.say_name]!")
    else:
        call process_character (n, appearance="pose behindhead face neutral blush false", text="Я думаю, что она собирается сыграть со мной в Храмы и Гидры!")
        call process_character (si, appearance="pose armunder face happy blush false", text="Вы любите играть в эту игру, не так ли?")
        call process_character (n, appearance="pose twohandfist face happy blush false", text="Да!")
        call process_character (n, appearance="pose twohandfist face happy blush false", text="Каждый раз мы создаём новых персонажей.")
        call process_character (n, appearance="pose twohandfist face happy blush false", text="Я собираюсь стать оборотнем в этой игре!")
        call process_character (si, appearance="pose handsup face neutral blush false", text="Как мило представить тебя оборотнем!")
        call process_character (n, appearance="pose handfist face neutral blush false", text="О, мой персонаж будет намного больше меня..")
        call process_character (n, appearance="pose handfist face neutral blush false", text="Я притворяюсь им в этой игре.")
        call process_character (si, appearance="pose handsfront face neutral blush false", text="А, понятно.")
        call process_character (si, appearance="pose handsfront face neutral blush false", text="Таким образом, ты становишься персонажем.")
        call process_character (n, appearance="pose handpocket face neutral blush false", text="Ага!")

    $ k.position = "right"
    call character_leave_dissolve (n)

    call process_character (k, appearance="outfit naked pose armsup face neutral blush false", text="{i}Фуух!{/i}")
    call process_character (k, appearance="outfit naked pose armsup face neutral blush false", text="В моей комнате так жарко!")
    call process_character (si, appearance="pose armunder face shock blush false", text="[k.say_name]!")
    call process_character (si, appearance="pose armunder face shock blush false", text="А где твоя одежда?!")
    call process_character (k, appearance="outfit naked pose handhip face neutral blush false", text="Мне было жарко, поэтому я сняла её.")
    call process_character (si, appearance="pose handsup face shock blush false", text="Так ты просто ходишь по дому голой?!")
    call process_character (k, appearance="outfit naked pose handhip face neutral blush false", text="Я всё время хожу в нижнем белье.")
    call process_character (k, appearance="outfit naked pose handhip face neutral blush false", text="Это не большая разница.")
    call process_character (si, appearance="pose handsup face embarrassed blush false", text="Это очень большая разница!")
    call process_character (k, appearance="outfit naked pose armcross face curious blush false", text="Мам, в чем проблема?")
    call process_character (k, appearance="outfit naked pose armcross face curious blush false", text="Это слишком неприглядно для [n.say_name] или что?")
    call process_character (k, appearance="outfit naked pose armcross face curious blush false", text="Ему нравится.")

    call character_leave_dissolve (k)
    call process_character (n, appearance="pose behindhead face curious blush false", text="...")

    call process_character (si, appearance="pose armunder face embarrassed blush false", text="Ну...")
    call process_character (si, appearance="pose armunder face embarrassed blush false", text="Несмотря на это...")

    call character_leave_dissolve (n)
    call process_character (k, appearance="outfit naked pose handhip face concerned blush false", text="Я не знаю, как ты можешь носить одежду в такую жару, мама!")
    call process_character (k, appearance="outfit naked pose handhip face neutral blush false", text="Ты должна быть голой, как я.")
    call process_character (si, appearance="pose armunder face shock blush false", text="Ч-что?!")
    call process_character (k, appearance="outfit naked pose armsup face flirt blush false", text="[n.say_name] это одобрит!")
    call process_character (k, appearance="outfit naked pose armsup face flirt blush false", text="Он увидит, как твои сиськи подпрыгивают, пока ты ходишь ...")
    call process_character (si, appearance="pose handsup face embarrassed blush true", text="Это неправильно, [k.say_name]!")
    call process_character (k, appearance="outfit naked pose armcross face neutral blush false", text="Мам, посмотри на его промежность...")

    call character_leave_dissolve (k)
    call process_character (n, appearance="outfit clothesjacket_hard pose behindhead face embarrassed blush false", text="...{p}...")

    call character_leave_dissolve (n)
    call process_character (k, appearance="outfit naked pose armcross face neutral blush false", text="Я наблюдала за ней.")
    call process_character (k, appearance="outfit naked pose armcross face neutral blush false", text="Как только он увидит, как ты ходишь голая...")
    call process_character (k, appearance="outfit naked pose armcross face flirt blush false", text="Можно будет разбивать палатку!")
    call process_character (si, appearance="pose handsfront face embarrassed blush false", text="...{p}...")
    call process_character (si, appearance="pose armunder face embarrassed blush false", text="(Его член готов вырваться из ширинки!)")
    call process_character (si, appearance="pose armunder face embarrassed blush false", text="...{p}...")
    call process_character (si, appearance="pose handsfront face concerned blush false", text="Извини, [n.say_name], но я не могу.")
    call process_character (si, appearance="pose handsfront face concerned blush false", text="А что если [julia.say_name] или [sa.say_name] увидят, как ты [k.say_name] и я ходим голыми. Что мы им скажем?")
    call process_character (k, appearance="outfit naked pose armsup face happy blush false", text="Присоединиться к маме!")
    call process_character (si, appearance="pose handsup face angry blush false", text="Достаточно, [k.say_name]!")
    call process_character (si, appearance="pose handsup face angry blush false", text="Пожалуйста, хотя бы надень бикини.")
    call process_character (k, appearance="outfit naked pose handhip face neutral blush false", text="Хорошо, хорошо.")
    call process_character (k, appearance="outfit naked pose handhip face neutral blush false", text="Я не хочу расстраивать тебя, Мам.")

    call character_leave_dissolve (k)
    call process_character (n, appearance="outfit clothesjacket_hard pose handpocket face concerned blush false", text="...")
    call process_character (k, appearance="outfit naked pose armcross face neutral blush false", text="Но эй, ты собираешься позаботиться о проблеме [n.say_name]?")
    call process_character (k, appearance="outfit naked pose armcross face flirt blush false", text="Или ты хочешь, чтобы я забрала его в свою комнату?")
    call process_character (si, appearance="pose armunder face embarrassed blush false", text="О-охх...")
    call process_character (si, appearance="pose armunder face embarrassed blush false", text="...")
    call process_character (si, appearance="pose handsup face neutral blush false", text="Я...")
    call process_character (si, appearance="pose handsup face neutral blush false", text="Я позабочусь об этом.")
    call process_character (k, appearance="outfit naked pose armsup face neutral blush false", text="Хотела бы я на это посмотреть, но мне надо одеться, пока [sa.say_name] или [julia.say_name] не увидели меня!")
    call process_character (k, appearance="outfit naked pose armsup face neutral blush false", text="О, и ещё, мама...")
    call process_character (k, appearance="outfit naked pose armsup face happy blush false", text="Если будешь дрочить ему, то вращай рукой его ствол, ему понравится!")
    call process_character (k, appearance="outfit naked pose armsup face happy blush false", text="Хорошо вам повеселиться!")

    call character_leave_dissolve (k)
    pause 0.5

    call process_character (n, appearance="outfit clothesjacket_hard pose behindhead face curious blush false", text="...")
    call process_character (si, appearance="pose armunder face concerned blush false", text="...")
    call process_character (si, appearance="pose armunder face concerned blush false", text="Твоя сестра знает, как завести разговор.")
    call process_character (n, appearance="outfit clothesjacket_hard pose handpocket face concerned blush false", text="Что?")
    call process_character (si, appearance="pose armunder face neutral blush false", text="Да ничего")
    call process_character (si, appearance="pose armunder face neutral blush false", text="...")
    call process_character (si, appearance="pose handsup face neutral blush false", text="Так ты хочешь, чтобы я подрочила тебе, милый?")
    call process_character (si, appearance="pose handsup face neutral blush false", text="Я обязательно сделаю то, что сказала [k.say_name], что тебе нравится.")
    call process_character (n, appearance="outfit clothesjacket_hard pose behindhead face curious blush false", text="...")
    call process_character (n, appearance="outfit clothesjacket_hard pose behindhead face curious blush false", text="Д-да...")

    call fade_to_black (0.5)
    "{i}Мама подрочила мне рукой, и я кончил на её руку.{/i}"

    $ reset_all_characters()

    if started_main_game:
        $ bust_art_background(stats.current_location.background())
        $ display_multiple_characters([ (n, ""), (si, "") ])

    call process_end_of_conversation ("simone_convo_15", si, default=False, priority=True, considered_scene=True)

    return