label janet_convo_default:
    call process_conversation_beginning ([ (n, ""), (janet, "") ])

    call debug_message ("Default conversation when none others are available.")
    $ janet.c("Привет " + n.say_name + ".")

    call process_end_of_conversation ("janet_convo_default", janet, priority=False, default=True)

    return


label janet_convo_1:
    call process_conversation_beginning ([ (n, ""), (janet, "pose handface face embarrassed blush false") ])

    call process_character (janet, appearance="pose handface face neutral blush false", text="Мне просто не везет на свиданиях!")
    call process_character (n, appearance="pose behindhead face neutral blush false", text="Тебе?")
    call process_character (janet, appearance="pose handhips face curious blush false", text="Мне кажется я притягиваю всяких психов.")
    call process_character (janet, appearance="pose handhips face curious blush false", text="Либо так, либо они хотят, чтобы я была послушной домохозяйкой.")
    call process_character (janet, appearance="pose handhips face curious blush false", text="Ну уж нет!")
    call process_character (n, appearance="pose handpocket face curious blush false", text="Так у тебя нет парня?")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Они просто отягащают меня сейчас.")
    call process_character (janet, appearance="pose handchest face neutral blush false", text="Когда ты встречаешься с мужчинами моего возраста, большинство из них уже не так активны.")
    call process_character (janet, appearance="pose handchest face shock blush false", text="И когда ты им предлагаешь сбросить вес или позаниматься на тренажёрах, они психуют!")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Чем старше они становятся, тем они упрямее.")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Я пробовала парней и помоложе.")
    call process_character (n, appearance="pose behindhead face neutral blush false", text="А с ними, что случилось?")
    call process_character (janet, appearance="pose handface face curious blush false", text="Это решает одну проблему, но создает другую.")
    call process_character (n, appearance="pose behindhead face curious blush false", text="Что ты имеешь в виду?")
    call process_character (janet, appearance="pose handface face neutral blush false", text="Молодые люди просто ещё не имеют никакого представления о том, что они хотят делать в своей жизни.")
    call process_character (janet, appearance="pose handface face neutral blush false", text="Они никогда не уверены, хотят ли они карьеру, семью, шикарную машину...")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Они говорят, в море полно рыбы...")
    call process_character (janet, appearance="pose handhips face embarrassed blush false", text="Но из того, что я находила, немногие были свежие.")
    call process_character (n, appearance="pose handpocket face concerned blush false", text="...")
    call process_character (janet, appearance="pose handchest face neutral blush false", text="Я думала, что будет легко вернуться на свиданки после развода.")
    call process_character (janet, appearance="pose handchest face neutral blush false", text="Я понимала какие качества искать, а какие избегать.")
    call process_character (janet, appearance="pose handhips face happy blush false", text="Но одинокая жизнь с каждым днём выглядит всё лучше и лучше!")
    call process_character (n, appearance="pose handpocket face neutral blush false", text="Да ну?")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Послушай моего совета, [n.say_name]...")
    call process_character (janet, appearance="pose handface face neutral blush false", text="Не выходи женись, когда ты молод и глуп!")
    call process_character (n, appearance="pose handpocket face curious blush false", text="...")

    call process_end_of_conversation ("janet_convo_1", janet, priority=False, default=False)


    return

label janet_convo_2:
    call process_conversation_beginning ([ (n, ""), (janet, "pose handface face neutral blush false") ])

    call process_character (janet, appearance="pose handface face neutral blush false", text="Я рада, что твоя Мама не купила дом рядом с пляжем.")
    call process_character (n, appearance="pose handpocket face curious blush false", text="Почему?")
    call process_character (janet, appearance="pose handface face shock blush false", text="Во-первых, налоги и страховка просто сумасшедшие!")
    call process_character (janet, appearance="pose handface face shock blush false", text="Ты должен увидеть, сколько твоя бабушка платит за месяц!")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="И вторая причина - прибрежные штормы.")
    call process_character (n, appearance="pose behindhead face curious blush false", text="Прибрежные штормы?")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Они могут быть принести много вреда.")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Порывы ветра, сильные ливни.")
    call process_character (janet, appearance="pose handchest face neutral blush false", text="Но для пляжников океан - это то, чего им нужно беспокоиться.")
    call process_character (n, appearance="pose handpocket face neutral blush false", text="Волны?")
    call process_character (janet, appearance="pose handchest face neutral blush false", text="Именно.")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="В прошлом году дом твоей бабушки почти смело.")
    call process_character (janet, appearance="pose handhips face shock blush false", text="Весь ее подвал затопило!")
    call process_character (n, appearance="pose handpocket face concerned blush false", text="Ого, правда?")
    call process_character (janet, appearance="pose handface face neutral blush false", text="Да, я ходила туда после шторма, чтобы проверить ее.")
    call process_character (janet, appearance="pose handface face concerned blush false", text="Страшно смотреть.")
    call process_character (janet, appearance="pose handface face concerned blush false", text="Понадобилось пару недель, чтобы убрать беспорядок.")
    call process_character (n, appearance="pose behindhead face curious blush false", text="Много бабушкиных вещей пострадало?")
    call process_character (janet, appearance="pose handhips face concerned blush false", text="К сожалению, да.")
    call process_character (janet, appearance="pose handhips face concerned blush false", text="Вода очень разрушительна.")
    call process_character (n, appearance="pose handpocket face concerned blush false", text="Думаешь, скоро будет ещё такой шторм?")
    call process_character (janet, appearance="pose handface face neutral blush false", text="В этом году, думаю, всё будет хорошо.")
    call process_character (janet, appearance="pose handface face neutral blush false", text="По данным прогноза, штормов не будет.")

    call process_character (n, appearance="pose handpocket face neutral blush false")

    call process_character (janet, appearance="pose handchest face neutral blush false", text="Это интересно следить за погодой.")
    call process_character (janet, appearance="pose handchest face neutral blush false", text="Я стала, как только начала проверять приливы и погодные условия для серфинга.")
    call process_character (n, appearance="pose handpocket face neutral blush false", text="А я даже не потрудился проверить погоду перед приездом.")
    call process_character (n, appearance="pose handfist face neutral blush false", text="Здесь всё время солнечно!")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Это правда.")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Но только потому, что солнечно, ещё не означает, что погода идеально подходит для серфинга.")
    call process_character (n, appearance="pose handpocket face neutral blush false", text="Почему?")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="В небе может быть и не облачка, но волны в окене могут быть огромными.")
    call process_character (janet, appearance="pose handface face neutral blush false", text="Обычно это происходит потому, что шторм в океане вызывает волны на берегу.")
    call process_character (janet, appearance="pose handface face neutral blush false", text="Разве это не интересно?")
    call process_character (n, appearance="pose behindhead face curious blush false", text="Ха, я вообще ничего об этом не знал.")
    call process_character (janet, appearance="pose handchest face happy blush false", text="Побудь со мной подольше, и ты станешь метеорологом!")

    call process_end_of_conversation ("janet_convo_2", janet, priority=False, default=False)


    return

label janet_convo_3:
    call process_conversation_beginning ([ (n, ""), (janet, "pose handhips face neutral blush false") ])

    call process_character (janet, appearance="pose handhips face neutral blush false", text="Мне нравится рано вставать, чтобы наблюдать восход солнца на пляже.")
    call process_character (janet, appearance="pose handhips face happy blush false", text="Можно сделать отличное фото!")
    call process_character (n, appearance="pose handpocket face neutral blush false", text="Да ну??")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Я фотографирую уже очень давно!")
    call process_character (janet, appearance="pose handchest face neutral blush false", text="Когда я только начинала, не было такого понятия, как цифровая фотография.")
    call process_character (janet, appearance="pose handchest face neutral blush false", text="Все снимали на пленку.")
    call process_character (janet, appearance="pose handface face neutral blush false", text="Ты, наверное, даже не знаешь, что такое пленочные камеры!")
    call process_character (n, appearance="pose behindhead face curious blush false", text="Пленочные камеры?")
    call process_character (n, appearance="pose behindhead face curious blush false", text="Они записывают видео и всё такое, как мой смартфон?")
    call process_character (janet, appearance="pose handface face happy blush false", text="Хаха!")
    call process_character (janet, appearance="pose handface face happy blush false", text="Не совсем так!")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Камера помещает фотографии на физический фрагмент пленки.")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Затем этот снимок обрабатывается в тёмной комнате, чтобы его можно было напечатать на бумаге или плакатах.")
    call process_character (n, appearance="pose handpocket face curious blush false", text="...")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Я знаю, ты лучше знаком с цифровыми вещами на компьютере.")
    call process_character (janet, appearance="pose handchest face neutral blush false", text="Многие старые фотографы были против перехода с плёнки.")

    call process_character (n, appearance="pose handpocket face neutral blush false")

    call process_character (janet, appearance="pose handchest face neutral blush false", text="Но я должна признать, что трудно превзойти удобство и гибкость цифровой техникик!")
    call process_character (n, appearance="pose handpocket face neutral blush false", text="Что ты фотографируешь?")
    call process_character (janet, appearance="pose handface face happy blush false", text="Все, что будет выглядеть хорошо, как на картине!")
    call process_character (janet, appearance="pose handface face neutral blush false", text="Иногда пейзажи, иногда людей...")
    call process_character (janet, appearance="pose handface face neutral blush false", text="Если кадр выглядит красивым, я сделаю снимок.")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="В течение многих лет это было моим хобби.")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Но теперь это действительно неплохой доход для меня!")
    call process_character (n, appearance="pose handfist face happy blush false", text="Здорово! Это круто, как ты можешь заработать деньги, делая это!")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Я много работаю внештатным сотрудником.")
    call process_character (janet, appearance="pose handchest face neutral blush false", text="Это означает, что меня нанимают различные компании, чтобы завершить работу для них.")
    call process_character (n, appearance="pose behindhead face neutral blush false", text="Какую работу ты выполняешь?")
    call process_character (janet, appearance="pose handface face neutral blush false", text="К примеру, съёмка публичного мероприятия или концерта.")
    call process_character (janet, appearance="pose handface face neutral blush false", text="Или, может быть, им нужно, чтобы я предоставил фотографии в рамках новостной статьи.")
    call process_character (janet, appearance="pose handchest face neutral blush false", text="Я узнал, что чем больше думаешь нестандартно, тем больше возможностей становится доступным.")
    call process_character (n, appearance="pose twohandfist face neutral blush false", text="Это звучит довольно весело!")
    call process_character (janet, appearance="pose handchest face happy blush false", text="Может, как-нибудь сфотографируешь восход солнца со мной?")
    call process_character (n, appearance="pose twohandfist face happy blush false", text="Круто!")
    call process_character (janet, appearance="pose handface face neutral blush false", text="Тебе придется рано вставать.")
    call process_character (janet, appearance="pose handface face neutral blush false", text="Я говорю о пяти тридцати утра.")
    call process_character (n, appearance="pose behindhead face embarrassed blush false", text="Это действительно рано......")
    call process_character (janet, appearance="pose handhips face happy blush false", text="Ты сова?")
    call process_character (n, appearance="pose behindhead face curious blush false", text="...")
    call process_character (n, appearance="pose behindhead face curious blush false", text="Иногда я не сплю допоздна, да.")
    call process_character (janet, appearance="pose handface face neutral blush false", text="Ты всегда можешь сфотографировать Луну.")
    call process_character (janet, appearance="pose handface face neutral blush false", text="Ты даже можешь получить несколько снимков Млечного пути, если достаточно темно!")
    call process_character (n, appearance="pose behindhead face happy blush false", text="Ух ты! Правда?")
    call process_character (janet, appearance="pose handhips face happy blush false", text="Это здорово, фотографировать метеоритный дождь!")

    call process_end_of_conversation ("janet_convo_3", janet, priority=False, default=False)


    return

label janet_convo_4:
    call process_conversation_beginning ([ (n, ""), (janet, "pose handface face neutral blush false") ])

    call process_character (janet, appearance="pose handface face neutral blush false", text="Так ты бегаешь с [k.say_name]?")
    call process_character (n, appearance="pose handpocket face neutral blush false", text="Да.")
    call process_character (n, appearance="pose handpocket face neutral blush false", text="Это довольно весело.")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Ну, это здорово, что вам это нравится!")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Редко можно увидеть людей, наслаждающихся физическими упражнениями.")
    call process_character (n, appearance="pose handfist face neutral blush false", text="Чем больше я бегаю, тем меньше устаю!")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Ты наращиваешь выносливость.")
    call process_character (janet, appearance="pose handchest face neutral blush false", text="Хотя, если ты спросишь моего мнения...")
    call process_character (janet, appearance="pose handchest face neutral blush false", text="Выносливость имеет много общего с диетой.")
    call process_character (n, appearance="pose behindhead face neutral blush false", text="Неужели?")
    call process_character (janet, appearance="pose handchest face curious blush false", text="Знаешь ли ты о том, что называется супер-едой?")
    call process_character (n, appearance="pose behindhead face curious blush false", text="Нет, что это?")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Она повышает энергию, способствует снижению веса, и помогает иммунной системе.")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Это всё что я покупаю, когда я хожу за продуктами.")
    call process_character (janet, appearance="pose handhips face happy blush false", text="Яйца являются одним из лучших суперпродуктов!")
    call process_character (janet, appearance="pose handhips face happy blush false", text="Я ем их каждый день.")

    if "julia_convo_3" in julia.conversations_completed:
        call process_character (n, appearance="pose handpocket face concerned blush false", text="[julia.say_name] сказала, что в вашем доме не так много еды.")
        call process_character (janet, appearance="pose handface face concerned blush false", text="Она рассказала тебе об этом?")
        call process_character (janet, appearance="pose handface face concerned blush false", text="У нас здесь много еды.")
        call process_character (n, appearance="pose handfist face neutral blush false", text="Да, похоже на то!")
        call process_character (janet, appearance="pose handface face curious blush false", text="Наш холодильник забит ею!")
        call process_character (janet, appearance="pose handface face curious blush false", text="Тогда почему [julia.say_name] сказала..")
        call process_character (janet, appearance="pose handchest face embarrassed blush false", text="Ох...")
        call process_character (janet, appearance="pose handchest face embarrassed blush false", text="Я знаю, почему она тебе это сказала...")
        call process_character (n, appearance="pose handpocket face curious blush false", text="Хм? Почему?")
        call process_character (janet, appearance="pose handhips face neutral blush false", text="[julia.say_name] не очень любит здоровую пищу.")
        call process_character (janet, appearance="pose handhips face neutral blush false", text="Но она любит нездоровую пищу.")
        call process_character (janet, appearance="pose handface face neutral blush false", text="Когда мы идем за покупками, она пытается пронести картофельные чипсы и печенье через кассу.")
        call process_character (n, appearance="pose handpocket face concerned blush false", text="Ты не разрешаешь ей это покупать?")
        call process_character (janet, appearance="pose handhips face angry blush false", text="Я не доверяю этому обработанному мусору.")
        call process_character (janet, appearance="pose handhips face angry blush false", text="Кто знает, какие консерванты и искусственный мусор они туда кладут!")
        call process_character (janet, appearance="pose handface face curious blush false", text="...")
        call process_character (janet, appearance="pose handface face curious blush false", text="Дай угадаю...")
        call process_character (janet, appearance="pose handface face curious blush false", text="Она просила арахисовое масло и мороженое?")
        call process_character (n, appearance="pose behindhead face curious blush false", text="...")
        call process_character (n, appearance="pose behindhead face curious blush false", text="Да, она действительно это сделала.")
        call process_character (janet, appearance="pose handhips face curious blush false", text="Ммм.")
        call process_character (janet, appearance="pose handhips face neutral blush false", text="Я не могу помешать ей есть то, что она хочет у тебя дома.")
        call process_character (janet, appearance="pose handface face neutral blush false", text="Ей просто нужно быть осторожной.")
        call process_character (janet, appearance="pose handface face happy blush false", text="[julia.say_name] думает, что останется в форме навсегда!")
        call process_character (n, appearance="pose handpocket face curious blush false", text="...")
    else:
        call process_character (n, appearance="pose handpocket face neutral blush false", text="Как насчет хлопьев?")
        call process_character (janet, appearance="pose handface face neutral blush false", text="Хлопья не плохие, но они не содержат много протеина.")
        call process_character (janet, appearance="pose handface face neutral blush false", text="В основном много сахара и углеводов.")
        call process_character (janet, appearance="pose handface face curious blush false", text="Вечером ты устаёшь быстрее, если были хлопья на завтрак?")
        call process_character (n, appearance="pose behindhead face neutral blush false", text="Хм, да, я быстро устаю.")
        call process_character (janet, appearance="pose handchest face neutral blush false", text="Хлопья вызывают это.")
        call process_character (janet, appearance="pose handchest face neutral blush false", text="Сахар заряжает энергией на короткое время, а потом БУМ.")
        call process_character (n, appearance="pose behindhead face curious blush false", text="Бум?")
        call process_character (janet, appearance="pose handhips face neutral blush false", text="Ты вырубаешься.")
        call process_character (n, appearance="pose handpocket face curious blush false", text="А, понятно.")
        call process_character (n, appearance="pose handpocket face curious blush false", text="Я не всегда ем хлопья по утрам.")


    call process_character (janet, appearance="pose handface face neutral blush false", text="Какую еду ты обычно ешь, [n.say_name], просто из любопытства?")
    call process_character (n, appearance="pose behindhead face neutral blush false", text="Много фруктов и овощей.")
    call process_character (n, appearance="pose behindhead face neutral blush false", text="Многие из них из сада моей мамы.")
    call process_character (janet, appearance="pose handhips face happy blush false", text="Это очень умно с ее стороны!")
    call process_character (janet, appearance="pose handhips face happy blush false", text="Нет ничего лучше, чем свежие продукты.")
    call process_character (janet, appearance="pose handhips face happy blush false", text="И это многое объясняет, почему ты такой худой!")
    call process_character (n, appearance="pose behindhead face concerned blush false", text="...")
    call process_character (janet, appearance="pose handface face neutral blush false", text="Я не говорю, что это плохо!")
    call process_character (janet, appearance="pose handface face neutral blush false", text="Я думала, ты худой, потому что тебя плохо кормят.")
    call process_character (janet, appearance="pose handface face happy blush false", text="Но это совсем не так!")
    call process_character (n, appearance="pose twohandfist face neutral blush false", text="Моя мама готовит очень вкусные блюда!")
    call process_character (n, appearance="pose twohandfist face neutral blush false", text="Она делает омлеты со всякой всячиной!")
    call process_character (janet, appearance="pose handchest face neutral blush false", text="Ты имеешь в виду шпинат, лук и тому подобное?")
    call process_character (n, appearance="pose twohandfist face happy blush false", text="Да, да!")
    call process_character (n, appearance="pose twohandfist face happy blush false", text="И еще она кладет туда немного сыра!")
    call process_character (janet, appearance="pose handchest face happy blush false", text="Я не знала, что она стала такой здоровой!")
    call process_character (janet, appearance="pose handchest face curious blush false", text="Интересно, она пытается похудеть?..")
    call process_character (n, appearance="pose handpocket face neutral blush false", text="Я знаю, что она занимается йогой.")
    call process_character (janet, appearance="pose handhips face shock blush false", text="Что она делает?!")
    call process_character (n, appearance="pose handfist face neutral blush false", text="Да.")
    call process_character (n, appearance="pose handfist face neutral blush false", text="Она старается делать это каждый день.")
    call process_character (janet, appearance="pose handface face happy blush false", text="Ух ты!")
    call process_character (janet, appearance="pose handface face happy blush false", text="Это та сторона твоей мамы, о которой я никогда не слышал!")
    call process_character (janet, appearance="pose handhips face happy blush false", text="В следующий раз я спрошу у нее рецепт омлета!")
    call process_character (janet, appearance="pose handhips face happy blush false", text="Я хотел бы попробовать его!")
    call process_character (janet, appearance="pose handchest face neutral blush false", text="Без сыра, конечно.")

    call process_end_of_conversation ("janet_convo_4", janet, priority=False, default=False)


    return

label janet_convo_5:
    call process_conversation_beginning ([ (n, ""), (janet, "pose handface face neutral blush false") ])

    call process_character (janet, appearance="pose handface face neutral blush false", text="Ты мне очень напоминаешь твою маму.")
    call process_character (n, appearance="pose behindhead face neutral blush false", text="Да?")
    call process_character (janet, appearance="pose handface face neutral blush false", text="У тебя много её черт.")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Ты внимательно слушаешь, запоминаешь много информации...")
    call process_character (janet, appearance="pose handhips face happy blush false", text="И ты заботишься о чувствах других людей.")
    call process_character (janet, appearance="pose handhips face happy blush false", text="Так же как твоя мама!")
    call process_character (n, appearance="pose behindhead face curious blush false", text="...")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Я знаю, что твоя мама не всегда любит мои грубые заявления.")
    call process_character (janet, appearance="pose handface face neutral blush false", text="Я уверена, она говорила тебе это раньше, когда меня не было рядом, верно?")
    call process_character (n, appearance="pose handpocket face concerned blush false", text="...")
    call process_character (janet, appearance="pose handface face neutral blush false", text="Я не люблю приукрашивать.")
    call process_character (janet, appearance="pose handface face neutral blush false", text="Я предпочитаю говорить всё, как есть!")
    call process_character (janet, appearance="pose handface face happy blush false", text="Потому что я бы хотела, чтобы со мной также говорили!")
    call process_character (n, appearance="pose behindhead face concerned blush false", text="Моя мама иногда раздражается, когда говорит о тебе.")
    call process_character (janet, appearance="pose handchest face neutral blush false", text="Она наверно еще помнит, что я сказала ей пару лет назад.")
    call process_character (janet, appearance="pose handchest face neutral blush false", text="Я не хотела быть грубой!")
    call process_character (n, appearance="pose handpocket face curious blush false", text="Что ты сказала?")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Когда я однажды её навещала, я заметила, что она прибавила в весе.")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Поэтому я спросила её об этом.")
    call process_character (n, appearance="pose handpocket face concerned blush false", text="И она разозлилась из-за этого?")
    call process_character (janet, appearance="pose handface face embarrassed blush false", text="Оглядываясь на это сейчас, я думаю, что это была последняя капля терпения.")
    call process_character (janet, appearance="pose handface face embarrassed blush false", text="Я точно не помню, что сказала, что-то вроде...")
    call process_character (janet, appearance="pose handhips face shock blush false", text="\"[si.say_name], ты растолстела! Ты должна сменить диету или физические упражнения, или всё вместе!\"")
    call process_character (n, appearance="pose behindhead face curious blush false", text="О...")
    call process_character (janet, appearance="pose handhips face sad blush false", text="Я думала она поймёт, что я забочусь о ней.")
    call process_character (janet, appearance="pose handhips face sad blush false", text="Но это обернулось не так, и она не говорила со мной до конца дня.")
    call process_character (n, appearance="pose behindhead face concerned blush false", text="Она разговаривала с тобой после этого?")
    call process_character (janet, appearance="pose handchest face neutral blush false", text="Ну конечно!")
    call process_character (janet, appearance="pose handchest face neutral blush false", text="Мы обе оставили это в прошлом, по большей части.")
    call process_character (janet, appearance="pose handface face neutral blush false", text="Но это всё ещё актуально.")
    call process_character (janet, appearance="pose handface face neutral blush false", text="И я знаю причину, почему.")
    call process_character (n, appearance="pose handpocket face concerned blush false", text="В чем причина?")
    call process_character (janet, appearance="pose handchest face neutral blush false", text="[si.say_name] и я обе знают, что в нашей семье быстро набирают весь.")
    call process_character (janet, appearance="pose handchest face neutral blush false", text="Именно поэтому я так строга со своей диетой!")
    call process_character (janet, appearance="pose handchest face neutral blush false", text="И я очень горжусь достижением, сбросив лишние килограммы!")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Я думаю, твоя мама думала, что я ткнула ей в лицо свою стройность.")
    call process_character (n, appearance="pose behindhead face curious blush false", text="Но ты этого не делала?")
    call process_character (janet, appearance="pose handchest face concerned blush false", text="Нет! Конечно, нет!")
    call process_character (janet, appearance="pose handchest face concerned blush false", text="Я бы никогда намеренно не сказала обидные вещи сестре!")
    call process_character (n, appearance="pose handpocket face concerned blush false", text="Ты пыталась объяснить это моей маме?")
    call process_character (janet, appearance="pose handface face neutral blush false", text="Я пробовал несколько раз.")
    call process_character (n, appearance="pose handpocket face concerned blush false", text="Это сработало?")
    call process_character (janet, appearance="pose handface face embarrassed blush false", text="Ммм, нуу...")
    call process_character (janet, appearance="pose handface face concerned blush false", text="Вес является чувствительной темой для многих женщин.")
    call process_character (janet, appearance="pose handface face concerned blush false", text="Так что, если я упомянула об этом даже при ней...")
    call process_character (janet, appearance="pose handhips face embarrassed blush false", text="Она ставит барьер, и не хочет продолжать разговор.")
    call process_character (n, appearance="pose behindhead face concerned blush false", text="...")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Однако я заметила, что она не прибавила в весе.")
    call process_character (janet, appearance="pose handhips face happy blush false", text="Так что это хороший знак, что она может предпринять шаги, чтобы предотвратить ухудшение, по крайней мере.")
    call process_character (n, appearance="pose handpocket face neutral blush false", text="...")
    call process_character (n, appearance="pose handfist face neutral blush false", text="Я думаю, тебе все еще стоит попробовать поговорить с ней снова.")
    call process_character (janet, appearance="pose handface face happy blush false", text="Ты - копия твоей Мамы!")
    call process_character (janet, appearance="pose handface face happy blush false", text="Вот доказательство этого!")
    call process_character (n, appearance="pose handpocket face curious blush false", text="...")
    call process_character (janet, appearance="pose handchest face neutral blush false", text="Тебе не нравится слышать о том, что мы с твоей мамой не ладим друг с другом.")
    call process_character (janet, appearance="pose handchest face neutral blush false", text="Я поговорю с ней еще раз, когда будет возможность, хорошо?")

    call process_character (n, appearance="pose handpocket face neutral blush false")

    call process_character (janet, appearance="pose handchest face happy blush false", text="Я сделаю это только для тебя [n.say_name]!")

    call process_end_of_conversation ("janet_convo_5", janet, priority=False, default=False)


    return

label janet_convo_6:
    call process_conversation_beginning ([ (n, ""), (janet, "pose handhips face neutral blush false") ])

    call process_character (janet, appearance="pose handhips face neutral blush false", text="Так чем ты любишь заниматься дома, [n.say_name]?")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Ты все еще играешь в эти видеоигры?")
    call process_character (n, appearance="pose handfist face neutral blush false", text="Да.")
    call process_character (n, appearance="pose handfist face neutral blush false", text="[sa.say_name] и я стримим наши игры.")
    call process_character (janet, appearance="pose handface face curious blush false", text="Стримим?")
    call process_character (janet, appearance="pose handface face curious blush false", text="Ты имеешь в виду, выкладываете в интернет видео вашей игры?")
    call process_character (n, appearance="pose handpocket face neutral blush false", text="Да, выкладываем.")
    call process_character (n, appearance="pose twohandfist face neutral blush false", text="Но стримя мы играем в игры вживую, с людьми, которые смотрят.")
    call process_character (janet, appearance="pose handface face curious blush false", text="А кто смотрит?")
    call process_character (n, appearance="pose behindhead face neutral blush false", text="Да кто угодно.")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Даже люди из других частей страны?")
    call process_character (n, appearance="pose handfist face neutral blush false", text="Даже люди со всего мира!")
    call process_character (janet, appearance="pose handhips face happy blush false", text="Нее...вероятно.")
    call process_character (janet, appearance="pose handhips face happy blush false", text="Технология невероятная штука, не так ли?")
    call process_character (n, appearance="pose twohandfist face happy blush false", text="Это супер весело!")
    call process_character (n, appearance="pose twohandfist face happy blush false", text="Мы подключаем микрофон и веб-камеру, и мы можем разговаривать и общаться с людьми, которые смотрят.")
    call process_character (janet, appearance="pose handface face neutral blush false", text="А я думала, что что-то знаю, используя свой смартфон...")
    call process_character (janet, appearance="pose handface face neutral blush false", text="Но это совсем не для меня!")
    call process_character (n, appearance="pose handpocket face neutral blush false", text="Это не так сложно, как ты думаешь, как только всё настроите.")
    call process_character (janet, appearance="pose handchest face happy blush false", text="Это потому, что ты привык к этому [n.say_name]!")
    call process_character (janet, appearance="pose handchest face happy blush false", text="Я неграмотный компьютерщик.")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Что я знаю, бесполезно даже для использования телефона.")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Но компьютеры гораздо труднее понять!")
    call process_character (n, appearance="pose behindhead face neutral blush false", text="Правда?")
    call process_character (n, appearance="pose behindhead face neutral blush false", text="Я не думаю, что их слишком сложно понять.")
    call process_character (n, appearance="pose handfist face neutral blush false", text="Может, я смогу научить тебя, как им пользоваться.")
    call process_character (janet, appearance="pose handface face neutral blush false", text="Если ты это сделаешь, тебе придется придётся начинать с азов!")
    call process_character (janet, appearance="pose handface face happy blush false", text="Все, что я знаю, это как нажать кнопку питания, чтобы включить его!")

    call process_end_of_conversation ("janet_convo_6", janet, priority=False, default=False)


    return

label janet_convo_7:

    if "janet_convo_4" in janet.conversations_completed:
        call process_conversation_beginning ([ (n, ""), (janet, "pose handhips face neutral blush false") ])
        call process_character (janet, appearance="pose handhips face neutral blush false", text="Когда твоя мама начала заниматься йогой?")
        call process_character (n, appearance="pose handpocket face neutral blush false", text="Не так давно это произошло.")
        call process_character (n, appearance="pose handpocket face neutral blush false", text="[k.say_name] втянула её в это.")
    else:
        call process_conversation_beginning ([ (n, ""), (janet, "pose handhips face neutral blush false") ])
        call process_character (janet, appearance="pose handhips face neutral blush false", text="[k.say_name] всё еще занимаетесь йогой?")
        call process_character (n, appearance="pose handpocket face neutral blush false", text="Думаю, да.")
        call process_character (n, appearance="pose handpocket face neutral blush false", text="Она делает много разных упражнений.")

    call process_character (janet, appearance="pose handchest face neutral blush false", text="[k.say_name] научилась йоге благодаря мне.")
    call process_character (n, appearance="pose behindhead face neutral blush false", text="Она научилась йоге у тебя?")
    call process_character (janet, appearance="pose handchest face neutral blush false", text="Однажды она увидела, как я этим занимаюсь, и очень заинтересовалась.")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Она мгновенно подсела.")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="С тех пор она всегда сосредоточена на улучшении своего тела и атлетизма.")
    call process_character (n, appearance="pose handpocket face neutral blush false", text="Как долго ты занимаешься йогой?")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Ох, на протяжении многих лет.")
    call process_character (janet, appearance="pose handface face neutral blush false", text="Изначально йога должна была помочь мне восстановиться после травмы, которую я получила.")
    call process_character (n, appearance="pose behindhead face concerned blush false", text="Ты поранилась?")
    call process_character (janet, appearance="pose handface face happy blush false", text="Теперь мне намного лучше!")
    call process_character (janet, appearance="pose handface face neutral blush false", text="Это было давным-давно.")
    call process_character (n, appearance="pose behindhead face curious blush false", text="Как это произошло?")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Сёрфинг.")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Я пыталась поймать волну, думая, что смогу опередить ее.")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Вместо этого она подняла меня и ударила прямо по спине и я упала на песок.")
    call process_character (n, appearance="pose handpocket face concerned blush false", text="Ой.")
    call process_character (janet, appearance="pose handface face neutral blush false", text="Было ой, ты прав.")
    call process_character (janet, appearance="pose handchest face neutral blush false", text="Волна выбила весь дух из меня!")
    call process_character (janet, appearance="pose handchest face neutral blush false", text="Ходить несколько недель было больно.")
    call process_character (n, appearance="pose behindhead face concerned blush false", text="Тебе нужно было ехать в больницу или еще куда?")
    call process_character (janet, appearance="pose handchest face neutral blush false", text="После того, как боль не уходила в течение нескольких дней, я пошла.")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Сначала я пошла к мануальному терапевту.")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Он сказал мне, что ничего не сломано, но мне нельзя перенапрягаться и беречь спину.")
    call process_character (n, appearance="pose handpocket face neutral blush false", text="Он сказал тебе о йоге?")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Он дал мне брошюру про различные техники йоги, чтобы облегчить боль в спине.")
    call process_character (janet, appearance="pose handchest face neutral blush false", text="В тот момент я вообще не верила в это.")
    call process_character (n, appearance="pose behindhead face neutral blush false", text="И ты не пошла?")
    call process_character (janet, appearance="pose handchest face neutral blush false", text="Я думала, что все эти сумасшедшие позы были просто пшиком.")
    call process_character (janet, appearance="pose handface face neutral blush false", text="Но я подумала, что лучше попробовать и посмотреть.")
    call process_character (janet, appearance="pose handface face happy blush false", text="Через пятнадцать минут, боль в спине резко снизилась!")
    call process_character (n, appearance="pose handfist face neutral blush false", text="Это круто!")
    call process_character (n, appearance="pose handfist face happy blush false", text="Это похоже на волшебство!")
    call process_character (janet, appearance="pose handhips face neutral blush false", text="Это связано с увеличением кровотока и кровообращения в суставах.")
    call process_character (janet, appearance="pose handhips face happy blush false", text="Так что никакой магии!")
    call process_character (janet, appearance="pose handhips face happy blush false", text="Я делаю это каждое утро, и это помогает завести моё тело утром!")

    call process_end_of_conversation ("janet_convo_7", janet, priority=False, default=False)


    return